# API routes package initialization

# Import all route modules for easy access
from app.api.routes import (
    auth,
    change_order_config,
    change_orders,
    control_accounts,
    cost_element_types,
    cost_elements,
    cost_event_types,
    cost_events,
    cost_registrations,
    dashboard,
    dashboard_layouts,
    evm,
    forecasts,
    notifications,
    organizational_units,
    progress_entries,
    projects,
    schedule_baselines,
    search,
    users,
    wbs_elements,
    work_packages,
)

__all__ = [
    "auth",
    "change_order_config",
    "change_orders",
    "control_accounts",
    "cost_element_types",
    "cost_elements",
    "cost_event_types",
    "cost_events",
    "cost_registrations",
    "dashboard",
    "dashboard_layouts",
    "evm",
    "forecasts",
    "notifications",
    "organizational_units",
    "progress_entries",
    "projects",
    "schedule_baselines",
    "search",
    "users",
    "wbs_elements",
    "work_packages",
]
