/**
 * E2E Test: Query Key Cache Coherency
 *
 * This test verifies that query keys generated by the centralized factory
 * maintain cache consistency across Time Machine context switches and mutations.
 *
 * Test Scenarios:
 * 1. Mutation in main branch invalidates main branch cache
 * 2. Time Machine context switch clears all versioned entity caches
 * 3. Historical view mutation doesn't affect current view cache
 * 4. Component-level invalidations include proper context parameters
 *
 * Run with: npm run e2e -- query-key-consistency.spec.ts
 */

import { test, expect } from "@playwright/test";

test.describe("Query Key Cache Coherency", () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to cost elements page
    await page.goto("/cost-elements");
    await expect(page.locator(".ant-table-wrapper")).toBeVisible();
  });

  test("should invalidate cache when updating cost element in current view", async ({
    page,
  }) => {
    // This test verifies that component-level mutations use factory keys
    // with proper Time Machine context (branch, asOf)

    const testCode = `CACHE-TEST-${Date.now()}`;

    // 1. Create a cost element
    await page.getByRole("button", { name: "Add Cost Element" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();

    await page.getByLabel("Cost Element Code").fill(testCode);
    await page.getByLabel("Name").fill("Cache Test Element");
    await page.getByLabel("Budget").fill("10000");

    await page.getByRole("button", { name: "Create" }).click();

    // 2. Wait for modal close and data refresh
    await expect(page.locator(".ant-modal-content")).not.toBeVisible();
    await expect(page.locator(`text=${testCode}`)).toBeVisible();

    // 3. Edit the cost element
    await page.locator(`tr:has-text("${testCode}")`).getByRole("button").nth(0).click();
    await expect(page.getByRole("dialog")).toBeVisible();

    await page.getByLabel("Budget").fill("15000");

    await page.getByRole("button", { name: "Save" }).click();

    // 4. Verify cache invalidated - new budget should show without page refresh
    await expect(page.locator(".ant-modal-content")).not.toBeVisible();
    await expect(page.locator(`text=€15,000`)).toBeVisible();

    // 5. Verify budget status also refreshed (dependent query invalidation)
    await page.locator(`tr:has-text("${testCode}")`).getByRole("button").nth(1).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(page.locator("text=Budget Status")).toBeVisible();
  });

  test("should clear caches when switching Time Machine context", async ({
    page,
  }) => {
    // This test verifies that Time Machine context switches use factory
    // 'all' keys to clear all versioned entity caches

    const testCode = `TM-TEST-${Date.now()}`;

    // 1. Create a cost element
    await page.getByRole("button", { name: "Add Cost Element" }).click();
    await page.getByLabel("Cost Element Code").fill(testCode);
    await page.getByLabel("Name").fill("Time Machine Test");
    await page.getByLabel("Budget").fill("20000");
    await page.getByRole("button", { name: "Create" }).click();
    await expect(page.locator(`text=${testCode}`)).toBeVisible();

    // 2. Switch Time Machine context to "as of" past date
    await page.getByRole("button", { name: "Time Machine" }).click();
    await page.getByLabel("As Of Date").fill("2024-01-01");
    await page.getByRole("button", { name: "Apply" }).click();

    // 3. Verify cache cleared - element should not appear (created after asOf date)
    await expect(page.locator(`text=${testCode}`)).not.toBeVisible();

    // 4. Switch back to current time
    await page.getByRole("button", { name: "Time Machine" }).click();
    await page.getByLabel("As Of Date").clear();
    await page.getByRole("button", { name: "Apply" }).click();

    // 5. Verify cache cleared and refetched - element should reappear
    await expect(page.locator(`text=${testCode}`)).toBeVisible();
  });

  test("should maintain separate caches for different branches", async ({
    page,
  }) => {
    // This test verifies that query keys include branch context
    // to prevent cache pollution across branches

    const testCode = `BRANCH-TEST-${Date.now()}`;

    // 1. Create cost element in main branch
    await page.getByRole("button", { name: "Add Cost Element" }).click();
    await page.getByLabel("Cost Element Code").fill(testCode);
    await page.getByLabel("Name").fill("Branch Test Element");
    await page.getByLabel("Budget").fill("30000");
    await page.getByRole("button", { name: "Create" }).click();
    await expect(page.locator(`text=${testCode}`)).toBeVisible();

    // 2. Switch to a feature branch (simulated via Time Machine)
    await page.getByRole("button", { name: "Time Machine" }).click();
    await page.getByLabel("Branch").selectOption("feature-branch");
    await page.getByRole("button", { name: "Apply" }).click();

    // 3. Verify cache isolation - element should not appear in different branch
    await expect(page.locator(`text=${testCode}`)).not.toBeVisible();

    // 4. Switch back to main branch
    await page.getByRole("button", { name: "Time Machine" }).click();
    await page.getByLabel("Branch").selectOption("main");
    await page.getByRole("button", { name: "Apply" }).click();

    // 5. Verify cache maintained - element should still be there
    await expect(page.locator(`text=${testCode}`)).toBeVisible();
  });

  test("should invalidate dependent queries after mutation", async ({
    page,
  }) => {
    // This test verifies that mutations invalidate dependent queries
    // (e.g., cost element changes → forecast invalidation)

    const testCode = `DEP-TEST-${Date.now()}`;

    // 1. Create cost element with budget
    await page.getByRole("button", { name: "Add Cost Element" }).click();
    await page.getByLabel("Cost Element Code").fill(testCode);
    await page.getByLabel("Name").fill("Dependency Test");
    await page.getByLabel("Budget").fill("50000");
    await page.getByRole("button", { name: "Create" }).click();
    await expect(page.locator(`text=${testCode}`)).toBeVisible();

    // 2. Navigate to Forecasts tab
    await page.locator(`tr:has-text("${testCode}")`).getByRole("link").click();
    await page.getByRole("tab", { name: "Forecasts" }).click();

    // 3. Create a forecast
    await page.getByRole("button", { name: "Add Forecast" }).click();
    await page.getByLabel("Estimate at Completion").fill("45000");
    await page.getByRole("button", { name: "Create" }).click();

    // 4. Verify forecast appears and EVM metrics are calculated
    await expect(page.locator("text=€45,000")).toBeVisible();
    await expect(page.locator("text=Variance")).toBeVisible();

    // 5. Update cost element budget
    await page.getByRole("tab", { name: "Overview" }).click();
    await page.locator(`button:has-text("Edit")`).first().click();
    await page.getByLabel("Budget").fill("60000");
    await page.getByRole("button", { name: "Save" }).click();

    // 6. Verify dependent forecast cache was invalidated
    await page.getByRole("tab", { name: "Forecasts" }).click();
    // EVM metrics should reflect new budget without manual refresh
    await expect(page.locator("text=Variance")).toBeVisible();
  });
});

test.describe("Query Key Factory Integration", () => {
  test("should use factory keys for all queries (verification)", async ({
    page,
  }) => {
    // This is a meta-test that verifies the query key factory is being used
    // by checking React Query DevTools query keys

    // 1. Navigate to cost elements
    await page.goto("/cost-elements");
    await expect(page.locator(".ant-table-wrapper")).toBeVisible();

    // 2. Open React Query DevTools
    await page.keyboard.press("Control+Shift+Q"); // Or use DevTools UI
    // Note: This requires DevTools to be enabled in development

    // 3. Verify query keys match factory pattern
    // Expected: ['cost-elements', 'all'] or ['cost-elements', 'detail', id, { branch, asOf }]
    // Not expected: ['cost_element', id] (old manual pattern)

    // This test is optional and requires DevTools inspection
    // In production, verify via code review and grep audit
  });
});
