"""System administration service for database dump and reseed operations.

Provides:
- dump_database(): Query all tables and serialize to seed_data.json-compatible dict
- validate_seed_data(): Validate seed data structure
- reseed_from_upload(): Validate, truncate, and reseed from uploaded JSON
"""

import logging
from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

# EVCS internal columns to exclude from dump — these are managed by the
# versioning framework and not present in the original seed_data.json schema.
_EVCS_EXCLUDE: set[str] = {
    "valid_time",
    "transaction_time",
}


def _serialize_value(value: Any) -> Any:
    """Convert a Python/DB value to a JSON-serializable type."""
    if value is None:
        return None
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, str)):
        return value
    if isinstance(value, dict):
        return {k: _serialize_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_serialize_value(v) for v in value]
    return str(value)


def _model_to_dict(instance: Any, exclude: set[str] | None = None) -> dict[str, Any]:
    """Serialize a SQLAlchemy model instance to a plain dict."""
    exclude = (exclude or set()) | _EVCS_EXCLUDE
    result: dict[str, Any] = {}
    # Use mapper columns to get only real DB columns (not relationships)
    mapper = type(instance).__mapper__
    for col in mapper.columns:
        col_name = col.key
        if col_name in exclude:
            continue
        value = getattr(instance, col_name, None)
        result[col_name] = _serialize_value(value)
    return result


class SystemAdminService:
    """Service for system admin operations: dump, validate, reseed."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def dump_database(self) -> dict[str, Any]:
        """Query all tables and return seed_data.json-compatible dict."""
        from app.models.domain.ai import (
            AIAssistantConfig,
            AIModel,
            AIProvider,
            AIProviderConfig,
        )
        from app.models.domain.change_order_config import (
            ChangeOrderApprovalRuleConfig,
            ChangeOrderImpactLevelConfig,
            ChangeOrderSLARuleConfig,
            ChangeOrderWorkflowConfig,
        )
        from app.models.domain.cost_element_type import CostElementType
        from app.models.domain.cost_event_type import CostEventType
        from app.models.domain.mcp_server import MCPServer
        from app.models.domain.organizational_unit import OrganizationalUnit
        from app.models.domain.rbac import RBACRole, RBACRolePermission
        from app.models.domain.user import User
        from app.models.domain.user_role_assignment import UserRoleAssignment
        from app.services.mcp_server_service import MCPServerService

        result: dict[str, Any] = {
            "_version": 1,
            "_comment": "Database dump generated by SystemAdminService",
        }

        # --- RBAC roles ---
        roles_result = await self.session.execute(
            select(RBACRole).order_by(RBACRole.name)
        )
        roles = list(roles_result.scalars().all())
        rbac_roles: dict[str, Any] = {}
        for role in roles:
            perms_result = await self.session.execute(
                select(RBACRolePermission.permission)
                .where(RBACRolePermission.role_id == role.id)
                .order_by(RBACRolePermission.permission)
            )
            permissions = sorted(row[0] for row in perms_result.all())
            rbac_roles[role.name] = {
                "description": role.description or "",
                "permissions": permissions,
            }
        result["rbac_roles"] = rbac_roles

        # --- Users ---
        users_result = await self.session.execute(select(User).order_by(User.email))
        users = list(users_result.scalars().all())
        result["users"] = [
            {
                "user_id": str(u.user_id),
                "email": u.email,
                "password": "",  # Omit hashed_password, placeholder
                "full_name": u.full_name,
            }
            for u in users
        ]

        # --- User role assignments (email -> role name) ---
        assignments_result = await self.session.execute(select(UserRoleAssignment))
        assignments = list(assignments_result.scalars().all())
        # Build user_id -> email map
        user_id_to_email: dict[UUID, str] = {u.user_id: u.email for u in users}
        # Build role_id -> role name map
        role_id_to_name: dict[UUID, str] = {r.id: r.name for r in roles}
        user_role_assignments: dict[str, str] = {}
        for a in assignments:
            if a.scope_type == "global":
                email = user_id_to_email.get(a.user_id)
                role_name = role_id_to_name.get(a.role_id)
                if email and role_name:
                    user_role_assignments[email] = role_name
        result["user_role_assignments"] = user_role_assignments

        # --- AI providers (with nested configs and models) ---
        providers_result = await self.session.execute(
            select(AIProvider).order_by(AIProvider.name)
        )
        providers = list(providers_result.scalars().all())
        ai_providers_data: list[dict[str, Any]] = []
        for provider in providers:
            provider_dict = _model_to_dict(
                provider, exclude={"created_at", "updated_at"}
            )
            provider_dict.pop("id", None)
            provider_dict["id"] = str(provider.id)

            # Fetch configs
            configs_result = await self.session.execute(
                select(AIProviderConfig).where(
                    AIProviderConfig.provider_id == str(provider.id)
                )
            )
            configs = []
            for cfg in configs_result.scalars().all():
                cfg_dict = _model_to_dict(cfg, exclude={"created_at", "updated_at"})
                cfg_dict.pop("id", None)
                cfg_dict["id"] = str(cfg.id)
                cfg_dict.pop("provider_id", None)
                configs.append(cfg_dict)
            provider_dict["configs"] = configs

            # Fetch models
            models_result = await self.session.execute(
                select(AIModel).where(AIModel.provider_id == str(provider.id))
            )
            models = []
            for mdl in models_result.scalars().all():
                mdl_dict = _model_to_dict(mdl, exclude={"created_at", "updated_at"})
                mdl_dict.pop("id", None)
                mdl_dict["id"] = str(mdl.id)
                mdl_dict.pop("provider_id", None)
                models.append(mdl_dict)
            provider_dict["models"] = models
            ai_providers_data.append(provider_dict)
        result["ai_providers"] = ai_providers_data

        # --- AI assistant configs (agent_type == "main") ---
        assistants_result = await self.session.execute(
            select(AIAssistantConfig)
            .where(AIAssistantConfig.agent_type == "main")
            .order_by(AIAssistantConfig.name)
        )
        result["ai_assistant_configs"] = [
            _model_to_dict(a, exclude={"created_at", "updated_at"})
            for a in assistants_result.scalars().all()
        ]

        # --- AI specialist configs (agent_type == "specialist") ---
        specialists_result = await self.session.execute(
            select(AIAssistantConfig)
            .where(AIAssistantConfig.agent_type == "specialist")
            .order_by(AIAssistantConfig.name)
        )
        result["ai_specialist_configs"] = [
            _model_to_dict(s, exclude={"created_at", "updated_at"})
            for s in specialists_result.scalars().all()
        ]

        # --- MCP servers (decrypt config) ---
        mcp_service = MCPServerService(self.session)
        mcp_result = await self.session.execute(
            select(MCPServer).order_by(MCPServer.name)
        )
        mcp_servers: list[dict[str, Any]] = []
        for srv in mcp_result.scalars().all():
            try:
                decrypted_config = mcp_service.decrypt_config(srv.config)
            except ValueError:
                decrypted_config = {}
            mcp_servers.append(
                {
                    "name": srv.name,
                    "config": decrypted_config,
                    "is_active": srv.is_active,
                }
            )
        result["mcp_servers"] = mcp_servers

        # --- Organizational units ---
        # --- Organizational units (current versions only) ---
        ou_result = await self.session.execute(
            select(OrganizationalUnit)
            .where(func.upper(OrganizationalUnit.valid_time).is_(None))
            .order_by(OrganizationalUnit.code)
        )
        result["organizational_units"] = [
            _model_to_dict(ou, exclude={"created_at", "updated_at"})
            for ou in ou_result.scalars().all()
        ]

        # --- Cost element types (current versions only) ---
        cet_result = await self.session.execute(
            select(CostElementType)
            .where(func.upper(CostElementType.valid_time).is_(None))
            .order_by(CostElementType.code)
        )
        result["cost_element_types"] = [
            _model_to_dict(cet, exclude={"created_at", "updated_at"})
            for cet in cet_result.scalars().all()
        ]

        # --- Cost event types (current versions only) ---
        cevt_result = await self.session.execute(
            select(CostEventType)
            .where(func.upper(CostEventType.valid_time).is_(None))
            .order_by(CostEventType.code)
        )
        result["cost_event_types"] = [
            _model_to_dict(cevt, exclude={"created_at", "updated_at"})
            for cevt in cevt_result.scalars().all()
        ]

        # --- Change order workflow ---
        co_config_result = await self.session.execute(select(ChangeOrderWorkflowConfig))
        co_config = co_config_result.scalar_one_or_none()
        if co_config is not None:
            config_dict = _model_to_dict(
                co_config, exclude={"created_at", "updated_at"}
            )
            # Fetch impact levels
            il_result = await self.session.execute(
                select(ChangeOrderImpactLevelConfig)
                .where(ChangeOrderImpactLevelConfig.config_id == co_config.id)
                .order_by(ChangeOrderImpactLevelConfig.level_order)
            )
            impact_levels = [
                _model_to_dict(il, exclude={"created_at", "updated_at"})
                for il in il_result.scalars().all()
            ]
            # Fetch approval rules
            ar_result = await self.session.execute(
                select(ChangeOrderApprovalRuleConfig).where(
                    ChangeOrderApprovalRuleConfig.config_id == co_config.id
                )
            )
            approval_rules = [
                _model_to_dict(ar, exclude={"created_at", "updated_at"})
                for ar in ar_result.scalars().all()
            ]
            # Fetch SLA rules
            sla_result = await self.session.execute(
                select(ChangeOrderSLARuleConfig).where(
                    ChangeOrderSLARuleConfig.config_id == co_config.id
                )
            )
            sla_rules = [
                _model_to_dict(sr, exclude={"created_at", "updated_at"})
                for sr in sla_result.scalars().all()
            ]
            result["change_order_workflow"] = {
                "config": config_dict,
                "impact_levels": impact_levels,
                "approval_rules": approval_rules,
                "sla_rules": sla_rules,
            }
        else:
            result["change_order_workflow"] = {
                "config": {},
                "impact_levels": [],
                "approval_rules": [],
                "sla_rules": [],
            }

        # --- Demo project data ---
        await self._dump_project_data(result)

        return result

    async def _dump_project_data(self, result: dict[str, Any]) -> None:
        """Dump all project-related entities into demo_project section."""
        from app.models.domain.change_order import ChangeOrder
        from app.models.domain.change_order_audit_log import ChangeOrderAuditLog
        from app.models.domain.control_account import ControlAccount
        from app.models.domain.cost_element import CostElement
        from app.models.domain.cost_event import CostEvent
        from app.models.domain.cost_registration import CostRegistration
        from app.models.domain.forecast import Forecast
        from app.models.domain.progress_entry import ProgressEntry
        from app.models.domain.project import Project
        from app.models.domain.schedule_baseline import ScheduleBaseline
        from app.models.domain.wbs_element import WBSElement
        from app.models.domain.work_package import WorkPackage

        # Query projects on main branch (current versions only)
        projects_result = await self.session.execute(
            select(Project)
            .where(
                Project.branch == "main",
                func.upper(Project.valid_time).is_(None),
            )
            .order_by(Project.project_id)
        )
        projects = list(projects_result.scalars().all())

        if not projects:
            result["demo_project"] = {}
            return

        # Use first project as the demo project section
        project = projects[0]
        project_dict = _model_to_dict(project, exclude={"created_at", "updated_at"})

        demo: dict[str, Any] = {
            "_comment": "Database dump",
            "_created_by": project_dict.get(
                "created_by", "00000000-0000-0000-0000-000000000001"
            ),
            "_dependency_order": [
                "project",
                "wbs_elements",
                "control_accounts",
                "work_packages",
                "cost_elements",
                "schedule_baselines",
                "forecasts",
                "progress_entries",
                "cost_events",
                "cost_registrations",
                "change_orders",
                "change_order_audit_logs",
            ],
            "project": project_dict,
        }

        # WBS elements (current versions only)
        wbs_result = await self.session.execute(
            select(WBSElement)
            .where(
                WBSElement.branch == "main",
                func.upper(WBSElement.valid_time).is_(None),
            )
            .order_by(WBSElement.wbs_element_id)
        )
        demo["wbs_elements"] = [
            _model_to_dict(w, exclude={"created_at", "updated_at"})
            for w in wbs_result.scalars().all()
        ]

        # Control accounts (current versions only)
        ca_result = await self.session.execute(
            select(ControlAccount)
            .where(
                ControlAccount.branch == "main",
                func.upper(ControlAccount.valid_time).is_(None),
            )
            .order_by(ControlAccount.control_account_id)
        )
        demo["control_accounts"] = [
            _model_to_dict(ca, exclude={"created_at", "updated_at"})
            for ca in ca_result.scalars().all()
        ]

        # Work packages (current versions only)
        wp_result = await self.session.execute(
            select(WorkPackage)
            .where(
                WorkPackage.branch == "main",
                func.upper(WorkPackage.valid_time).is_(None),
            )
            .order_by(WorkPackage.work_package_id)
        )
        demo["work_packages"] = [
            _model_to_dict(wp, exclude={"created_at", "updated_at"})
            for wp in wp_result.scalars().all()
        ]

        # Cost elements (current versions only)
        ce_result = await self.session.execute(
            select(CostElement)
            .where(func.upper(CostElement.valid_time).is_(None))
            .order_by(CostElement.cost_element_id)
        )
        demo["cost_elements"] = [
            _model_to_dict(ce, exclude={"created_at", "updated_at"})
            for ce in ce_result.scalars().all()
        ]

        # Schedule baselines (current versions only)
        sb_result = await self.session.execute(
            select(ScheduleBaseline)
            .where(
                ScheduleBaseline.branch == "main",
                func.upper(ScheduleBaseline.valid_time).is_(None),
            )
            .order_by(ScheduleBaseline.schedule_baseline_id)
        )
        demo["schedule_baselines"] = [
            _model_to_dict(sb, exclude={"created_at", "updated_at"})
            for sb in sb_result.scalars().all()
        ]

        # Forecasts (current versions only)
        fc_result = await self.session.execute(
            select(Forecast)
            .where(
                Forecast.branch == "main",
                func.upper(Forecast.valid_time).is_(None),
            )
            .order_by(Forecast.forecast_id)
        )
        demo["forecasts"] = [
            _model_to_dict(fc, exclude={"created_at", "updated_at"})
            for fc in fc_result.scalars().all()
        ]

        # Progress entries (current versions only)
        pe_result = await self.session.execute(
            select(ProgressEntry)
            .where(func.upper(ProgressEntry.valid_time).is_(None))
            .order_by(ProgressEntry.progress_entry_id)
        )
        demo["progress_entries"] = [
            _model_to_dict(pe, exclude={"created_at", "updated_at"})
            for pe in pe_result.scalars().all()
        ]

        # Cost events (current versions only)
        cost_evt_result = await self.session.execute(
            select(CostEvent)
            .where(func.upper(CostEvent.valid_time).is_(None))
            .order_by(CostEvent.cost_event_id)
        )
        demo["cost_events"] = [
            _model_to_dict(evt, exclude={"created_at", "updated_at"})
            for evt in cost_evt_result.scalars().all()
        ]

        # Cost registrations (current versions only)
        cr_result = await self.session.execute(
            select(CostRegistration)
            .where(func.upper(CostRegistration.valid_time).is_(None))
            .order_by(CostRegistration.cost_registration_id)
        )
        demo["cost_registrations"] = [
            _model_to_dict(cr, exclude={"created_at", "updated_at"})
            for cr in cr_result.scalars().all()
        ]

        # Change orders (current versions only)
        co_result = await self.session.execute(
            select(ChangeOrder)
            .where(
                ChangeOrder.branch == "main",
                func.upper(ChangeOrder.valid_time).is_(None),
            )
            .order_by(ChangeOrder.change_order_id)
        )
        demo["change_orders"] = [
            _model_to_dict(co, exclude={"created_at", "updated_at"})
            for co in co_result.scalars().all()
        ]

        # Change order audit logs
        co_audit_result = await self.session.execute(
            select(ChangeOrderAuditLog).order_by(ChangeOrderAuditLog.changed_at)
        )
        demo["change_order_audit_logs"] = [
            _model_to_dict(al, exclude={"created_at", "updated_at"})
            for al in co_audit_result.scalars().all()
        ]

        result["demo_project"] = demo

    @staticmethod
    def validate_seed_data(data: dict[str, Any]) -> list[str]:
        """Validate seed data structure. Returns list of errors (empty = valid)."""
        errors: list[str] = []

        if "_version" not in data:
            errors.append("Missing '_version' field")
        elif not isinstance(data["_version"], int):
            errors.append("'_version' must be an integer")

        required_sections = [
            "rbac_roles",
            "users",
            "user_role_assignments",
            "ai_providers",
            "ai_assistant_configs",
            "ai_specialist_configs",
            "mcp_servers",
            "organizational_units",
            "cost_element_types",
            "cost_event_types",
            "change_order_workflow",
            "demo_project",
        ]

        for section in required_sections:
            if section not in data:
                errors.append(f"Missing required section: '{section}'")

        # Validate rbac_roles structure
        if "rbac_roles" in data and isinstance(data["rbac_roles"], dict):
            for role_name, role_def in data["rbac_roles"].items():
                if not isinstance(role_def, dict):
                    errors.append(f"rbac_roles['{role_name}'] must be a dict")
                    continue
                if "description" not in role_def:
                    errors.append(f"rbac_roles['{role_name}'] missing 'description'")
                if "permissions" not in role_def:
                    errors.append(f"rbac_roles['{role_name}'] missing 'permissions'")
                elif not isinstance(role_def["permissions"], list):
                    errors.append(
                        f"rbac_roles['{role_name}']['permissions'] must be a list"
                    )

        # Validate users structure
        if "users" in data and isinstance(data["users"], list):
            for i, user in enumerate(data["users"]):
                if not isinstance(user, dict):
                    errors.append(f"users[{i}] must be a dict")
                    continue
                for field in ("user_id", "email", "password", "full_name"):
                    if field not in user:
                        errors.append(f"users[{i}] missing '{field}'")

        # Validate user_role_assignments structure
        if "user_role_assignments" in data:
            if not isinstance(data["user_role_assignments"], dict):
                errors.append("user_role_assignments must be a dict")

        # Validate demo_project structure
        if "demo_project" in data and isinstance(data["demo_project"], dict):
            dp = data["demo_project"]
            if "_created_by" not in dp:
                errors.append("demo_project missing '_created_by'")
            if "_dependency_order" not in dp:
                errors.append("demo_project missing '_dependency_order'")
            if "project" not in dp:
                errors.append("demo_project missing 'project'")

        return errors

    async def reseed_from_upload(self, data: dict[str, Any]) -> dict[str, Any]:
        """Validate, truncate, and reseed from uploaded JSON.

        Returns a summary dict with counts of seeded entities.
        """
        from app.db.reseed import reseed_from_data, truncate_all_tables

        # 1. Validate
        errors = self.validate_seed_data(data)
        if errors:
            return {"success": False, "errors": errors}

        # 2. Truncate
        await truncate_all_tables()

        # 3. Reseed
        await reseed_from_data(self.session, data)

        # 4. Build summary
        summary: dict[str, Any] = {"success": True}
        summary["users"] = len(data.get("users", []))
        summary["rbac_roles"] = len(data.get("rbac_roles", {}))
        summary["ai_providers"] = len(data.get("ai_providers", []))
        summary["ai_assistant_configs"] = len(data.get("ai_assistant_configs", []))
        summary["ai_specialist_configs"] = len(data.get("ai_specialist_configs", []))
        summary["mcp_servers"] = len(data.get("mcp_servers", []))
        summary["organizational_units"] = len(data.get("organizational_units", []))
        summary["cost_element_types"] = len(data.get("cost_element_types", []))
        summary["cost_event_types"] = len(data.get("cost_event_types", []))
        demo = data.get("demo_project", {})
        if isinstance(demo, dict):
            summary["demo_project_entities"] = {
                key: len(val) for key, val in demo.items() if isinstance(val, list)
            }
        return summary
