"""System administration service for database dump and reseed operations.

Provides:
- dump_database(): Query all tables and serialize to two-section dump dict
- validate_seed_data(): Validate seed data structure
- reseed_from_upload(): Validate, truncate, and reseed from uploaded JSON
"""

import logging
from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

# EVCS internal columns to exclude from dump — these are managed by the
# versioning framework and not present in the original seed_data.json schema.
_EVCS_EXCLUDE: set[str] = {
    "valid_time",
    "transaction_time",
}


def _serialize_value(value: Any) -> Any:
    """Convert a Python/DB value to a JSON-serializable type."""
    if value is None:
        return None
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, str)):
        return value
    if isinstance(value, dict):
        return {k: _serialize_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_serialize_value(v) for v in value]
    return str(value)


def _model_to_dict(instance: Any, exclude: set[str] | None = None) -> dict[str, Any]:
    """Serialize a SQLAlchemy model instance to a plain dict."""
    exclude = (exclude or set()) | _EVCS_EXCLUDE
    result: dict[str, Any] = {}
    # Use mapper columns to get only real DB columns (not relationships)
    mapper = type(instance).__mapper__
    for col in mapper.columns:
        col_name = col.key
        if col_name in exclude:
            continue
        value = getattr(instance, col_name, None)
        result[col_name] = _serialize_value(value)
    return result


class SystemAdminService:
    """Service for system admin operations: dump, validate, reseed."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def dump_database(self) -> dict[str, Any]:
        """Query all tables and return a two-section dump dict.

        Returns a dict with two top-level sections:
        - ``system_config``: RBAC, users, AI config, MCP servers, CO workflow
        - ``projects``: All project entities as flat top-level arrays
        """
        system_config = await self._dump_system_config()
        projects = await self._dump_projects_data()
        return {
            "_version": 1,
            "_comment": "Database dump generated by SystemAdminService",
            "system_config": system_config,
            "projects": projects,
        }

    async def _dump_system_config(self) -> dict[str, Any]:
        """Dump system configuration: RBAC, users, AI, MCP, CO workflow."""
        from app.models.domain.ai import (
            AIAssistantConfig,
            AIModel,
            AIProvider,
            AIProviderConfig,
        )
        from app.models.domain.change_order_config import (
            ChangeOrderApprovalRuleConfig,
            ChangeOrderImpactLevelConfig,
            ChangeOrderSLARuleConfig,
            ChangeOrderWorkflowConfig,
        )
        from app.models.domain.mcp_server import MCPServer
        from app.models.domain.rbac import RBACRole, RBACRolePermission
        from app.models.domain.user import User
        from app.models.domain.user_role_assignment import UserRoleAssignment
        from app.services.mcp_server_service import MCPServerService

        result: dict[str, Any] = {}

        # --- RBAC roles ---
        roles_result = await self.session.execute(
            select(RBACRole).order_by(RBACRole.name)
        )
        roles = list(roles_result.scalars().all())
        rbac_roles: dict[str, Any] = {}
        for role in roles:
            perms_result = await self.session.execute(
                select(RBACRolePermission.permission)
                .where(RBACRolePermission.role_id == role.id)
                .order_by(RBACRolePermission.permission)
            )
            permissions = sorted(row[0] for row in perms_result.all())
            rbac_roles[role.name] = {
                "description": role.description or "",
                "permissions": permissions,
            }
        result["rbac_roles"] = rbac_roles

        # --- Users ---
        users_result = await self.session.execute(select(User).order_by(User.email))
        users = list(users_result.scalars().all())
        result["users"] = [
            {
                "user_id": str(u.user_id),
                "email": u.email,
                "password": "",  # Omit hashed_password, placeholder
                "full_name": u.full_name,
            }
            for u in users
        ]

        # --- User role assignments (email -> role name) ---
        assignments_result = await self.session.execute(select(UserRoleAssignment))
        assignments = list(assignments_result.scalars().all())
        user_id_to_email: dict[UUID, str] = {u.user_id: u.email for u in users}
        role_id_to_name: dict[UUID, str] = {r.id: r.name for r in roles}
        user_role_assignments: dict[str, str] = {}
        for a in assignments:
            if a.scope_type == "global":
                email = user_id_to_email.get(a.user_id)
                role_name = role_id_to_name.get(a.role_id)
                if email and role_name:
                    user_role_assignments[email] = role_name
        result["user_role_assignments"] = user_role_assignments

        # --- AI providers (with nested configs and models) ---
        providers_result = await self.session.execute(
            select(AIProvider).order_by(AIProvider.name)
        )
        providers = list(providers_result.scalars().all())
        ai_providers_data: list[dict[str, Any]] = []
        for provider in providers:
            provider_dict = _model_to_dict(
                provider, exclude={"created_at", "updated_at"}
            )
            provider_dict.pop("id", None)
            provider_dict["id"] = str(provider.id)

            configs_result = await self.session.execute(
                select(AIProviderConfig).where(
                    AIProviderConfig.provider_id == str(provider.id)
                )
            )
            configs = []
            for cfg in configs_result.scalars().all():
                cfg_dict = _model_to_dict(cfg, exclude={"created_at", "updated_at"})
                cfg_dict.pop("id", None)
                cfg_dict["id"] = str(cfg.id)
                cfg_dict.pop("provider_id", None)
                configs.append(cfg_dict)
            provider_dict["configs"] = configs

            models_result = await self.session.execute(
                select(AIModel).where(AIModel.provider_id == str(provider.id))
            )
            models = []
            for mdl in models_result.scalars().all():
                mdl_dict = _model_to_dict(mdl, exclude={"created_at", "updated_at"})
                mdl_dict.pop("id", None)
                mdl_dict["id"] = str(mdl.id)
                mdl_dict.pop("provider_id", None)
                models.append(mdl_dict)
            provider_dict["models"] = models
            ai_providers_data.append(provider_dict)
        result["ai_providers"] = ai_providers_data

        # --- AI assistant configs (agent_type == "main") ---
        assistants_result = await self.session.execute(
            select(AIAssistantConfig)
            .where(AIAssistantConfig.agent_type == "main")
            .order_by(AIAssistantConfig.name)
        )
        result["ai_assistant_configs"] = [
            _model_to_dict(a, exclude={"created_at", "updated_at"})
            for a in assistants_result.scalars().all()
        ]

        # --- AI specialist configs (agent_type == "specialist") ---
        specialists_result = await self.session.execute(
            select(AIAssistantConfig)
            .where(AIAssistantConfig.agent_type == "specialist")
            .order_by(AIAssistantConfig.name)
        )
        result["ai_specialist_configs"] = [
            _model_to_dict(s, exclude={"created_at", "updated_at"})
            for s in specialists_result.scalars().all()
        ]

        # --- MCP servers (decrypt config) ---
        mcp_service = MCPServerService(self.session)
        mcp_result = await self.session.execute(
            select(MCPServer).order_by(MCPServer.name)
        )
        mcp_servers: list[dict[str, Any]] = []
        for srv in mcp_result.scalars().all():
            try:
                decrypted_config = mcp_service.decrypt_config(srv.config)
            except ValueError:
                decrypted_config = {}
            mcp_servers.append(
                {
                    "name": srv.name,
                    "config": decrypted_config,
                    "is_active": srv.is_active,
                }
            )
        result["mcp_servers"] = mcp_servers

        # --- Change order workflow ---
        # Global config only — per-project overrides (project_id != NULL)
        # are not part of the single-config system_config dump/reseed format.
        global_configs_result = await self.session.execute(
            select(ChangeOrderWorkflowConfig)
            .where(ChangeOrderWorkflowConfig.project_id.is_(None))
            .order_by(ChangeOrderWorkflowConfig.created_at)
        )
        global_configs = list(global_configs_result.scalars().all())
        co_config = None
        if global_configs:
            # Prefer the config that actually has child rules; an empty
            # duplicate global can exist alongside the populated seed config.
            co_config = next(
                (
                    c
                    for c in global_configs
                    if c.impact_levels or c.approval_rules or c.sla_rules
                ),
                global_configs[0],
            )
            if len(global_configs) > 1:
                logger.warning(
                    "Multiple global change-order workflow configs found (%d); "
                    "exporting %s",
                    len(global_configs),
                    co_config.id,
                )
        if co_config is not None:
            config_dict = _model_to_dict(
                co_config, exclude={"created_at", "updated_at"}
            )
            il_result = await self.session.execute(
                select(ChangeOrderImpactLevelConfig)
                .where(ChangeOrderImpactLevelConfig.config_id == co_config.id)
                .order_by(ChangeOrderImpactLevelConfig.level_order)
            )
            impact_levels = [
                _model_to_dict(il, exclude={"created_at", "updated_at"})
                for il in il_result.scalars().all()
            ]
            ar_result = await self.session.execute(
                select(ChangeOrderApprovalRuleConfig).where(
                    ChangeOrderApprovalRuleConfig.config_id == co_config.id
                )
            )
            approval_rules = [
                _model_to_dict(ar, exclude={"created_at", "updated_at"})
                for ar in ar_result.scalars().all()
            ]
            sla_result = await self.session.execute(
                select(ChangeOrderSLARuleConfig).where(
                    ChangeOrderSLARuleConfig.config_id == co_config.id
                )
            )
            sla_rules = [
                _model_to_dict(sr, exclude={"created_at", "updated_at"})
                for sr in sla_result.scalars().all()
            ]
            result["change_order_workflow"] = {
                "config": config_dict,
                "impact_levels": impact_levels,
                "approval_rules": approval_rules,
                "sla_rules": sla_rules,
            }
        else:
            result["change_order_workflow"] = {
                "config": {},
                "impact_levels": [],
                "approval_rules": [],
                "sla_rules": [],
            }

        return result

    async def _dump_projects_data(self) -> dict[str, Any]:
        """Dump all project-related entities as flat top-level arrays."""
        from app.models.domain.branch import Branch
        from app.models.domain.change_order import ChangeOrder
        from app.models.domain.change_order_audit_log import ChangeOrderAuditLog
        from app.models.domain.control_account import ControlAccount
        from app.models.domain.cost_element import CostElement
        from app.models.domain.cost_element_type import CostElementType
        from app.models.domain.cost_event import CostEvent
        from app.models.domain.cost_event_type import CostEventType
        from app.models.domain.cost_registration import CostRegistration
        from app.models.domain.forecast import Forecast
        from app.models.domain.organizational_unit import OrganizationalUnit
        from app.models.domain.progress_entry import ProgressEntry
        from app.models.domain.project import Project
        from app.models.domain.project_budget_settings import ProjectBudgetSettings
        from app.models.domain.schedule_baseline import ScheduleBaseline
        from app.models.domain.schedule_dependency import ScheduleDependency
        from app.models.domain.wbs_element import WBSElement
        from app.models.domain.work_package import WorkPackage

        result: dict[str, Any] = {}

        # --- Organizational units (current versions only) ---
        ou_result = await self.session.execute(
            select(OrganizationalUnit)
            .where(func.upper(OrganizationalUnit.valid_time).is_(None))
            .order_by(OrganizationalUnit.code)
        )
        result["organizational_units"] = [
            _model_to_dict(ou, exclude={"created_at", "updated_at"})
            for ou in ou_result.scalars().all()
        ]

        # --- Cost element types (current versions only) ---
        cet_result = await self.session.execute(
            select(CostElementType)
            .where(func.upper(CostElementType.valid_time).is_(None))
            .order_by(CostElementType.code)
        )
        result["cost_element_types"] = [
            _model_to_dict(cet, exclude={"created_at", "updated_at"})
            for cet in cet_result.scalars().all()
        ]

        # --- Cost event types (current versions only) ---
        cevt_result = await self.session.execute(
            select(CostEventType)
            .where(func.upper(CostEventType.valid_time).is_(None))
            .order_by(CostEventType.code)
        )
        result["cost_event_types"] = [
            _model_to_dict(cevt, exclude={"created_at", "updated_at"})
            for cevt in cevt_result.scalars().all()
        ]

        # --- Projects (all projects on main branch, current versions only) ---
        projects_result = await self.session.execute(
            select(Project)
            .where(
                Project.branch == "main",
                func.upper(Project.valid_time).is_(None),
            )
            .order_by(Project.project_id)
        )
        result["projects"] = [
            _model_to_dict(p, exclude={"created_at", "updated_at"})
            for p in projects_result.scalars().all()
        ]

        # --- Project budget settings (current versions only) ---
        pbs_result = await self.session.execute(
            select(ProjectBudgetSettings)
            .where(func.upper(ProjectBudgetSettings.valid_time).is_(None))
            .order_by(ProjectBudgetSettings.project_budget_settings_id)
        )
        result["project_budget_settings"] = [
            _model_to_dict(pbs, exclude={"created_at", "updated_at"})
            for pbs in pbs_result.scalars().all()
        ]

        # --- Branches (current versions only) ---
        branches_result = await self.session.execute(
            select(Branch)
            .where(func.upper(Branch.valid_time).is_(None))
            .order_by(Branch.branch_id)
        )
        result["branches"] = [
            _model_to_dict(b, exclude={"created_at", "updated_at"})
            for b in branches_result.scalars().all()
        ]

        # --- WBS elements (current versions only) ---
        wbs_result = await self.session.execute(
            select(WBSElement)
            .where(
                WBSElement.branch == "main",
                func.upper(WBSElement.valid_time).is_(None),
            )
            .order_by(WBSElement.wbs_element_id)
        )
        result["wbs_elements"] = [
            _model_to_dict(w, exclude={"created_at", "updated_at"})
            for w in wbs_result.scalars().all()
        ]

        # --- Control accounts (current versions only) ---
        ca_result = await self.session.execute(
            select(ControlAccount)
            .where(
                ControlAccount.branch == "main",
                func.upper(ControlAccount.valid_time).is_(None),
            )
            .order_by(ControlAccount.control_account_id)
        )
        result["control_accounts"] = [
            _model_to_dict(ca, exclude={"created_at", "updated_at"})
            for ca in ca_result.scalars().all()
        ]

        # --- Work packages (current versions only) ---
        wp_result = await self.session.execute(
            select(WorkPackage)
            .where(
                WorkPackage.branch == "main",
                func.upper(WorkPackage.valid_time).is_(None),
            )
            .order_by(WorkPackage.work_package_id)
        )
        result["work_packages"] = [
            _model_to_dict(wp, exclude={"created_at", "updated_at"})
            for wp in wp_result.scalars().all()
        ]

        # --- Cost elements (current versions only) ---
        ce_result = await self.session.execute(
            select(CostElement)
            .where(func.upper(CostElement.valid_time).is_(None))
            .order_by(CostElement.cost_element_id)
        )
        result["cost_elements"] = [
            _model_to_dict(ce, exclude={"created_at", "updated_at"})
            for ce in ce_result.scalars().all()
        ]

        # --- Schedule baselines (current versions only) ---
        sb_result = await self.session.execute(
            select(ScheduleBaseline)
            .where(
                ScheduleBaseline.branch == "main",
                func.upper(ScheduleBaseline.valid_time).is_(None),
            )
            .order_by(ScheduleBaseline.schedule_baseline_id)
        )
        result["schedule_baselines"] = [
            _model_to_dict(sb, exclude={"created_at", "updated_at"})
            for sb in sb_result.scalars().all()
        ]

        # --- Schedule dependencies ---
        sd_result = await self.session.execute(
            select(ScheduleDependency).order_by(
                ScheduleDependency.schedule_dependency_id
            )
        )
        result["schedule_dependencies"] = [
            _model_to_dict(sd, exclude={"created_at", "updated_at"})
            for sd in sd_result.scalars().all()
        ]

        # --- Forecasts (current versions only) ---
        fc_result = await self.session.execute(
            select(Forecast)
            .where(
                Forecast.branch == "main",
                func.upper(Forecast.valid_time).is_(None),
            )
            .order_by(Forecast.forecast_id)
        )
        result["forecasts"] = [
            _model_to_dict(fc, exclude={"created_at", "updated_at"})
            for fc in fc_result.scalars().all()
        ]

        # --- Progress entries (current versions only) ---
        pe_result = await self.session.execute(
            select(ProgressEntry)
            .where(func.upper(ProgressEntry.valid_time).is_(None))
            .order_by(ProgressEntry.progress_entry_id)
        )
        result["progress_entries"] = [
            _model_to_dict(pe, exclude={"created_at", "updated_at"})
            for pe in pe_result.scalars().all()
        ]

        # --- Cost events (current versions only) ---
        cost_evt_result = await self.session.execute(
            select(CostEvent)
            .where(func.upper(CostEvent.valid_time).is_(None))
            .order_by(CostEvent.cost_event_id)
        )
        result["cost_events"] = [
            _model_to_dict(evt, exclude={"created_at", "updated_at"})
            for evt in cost_evt_result.scalars().all()
        ]

        # --- Cost registrations (current versions only) ---
        cr_result = await self.session.execute(
            select(CostRegistration)
            .where(func.upper(CostRegistration.valid_time).is_(None))
            .order_by(CostRegistration.cost_registration_id)
        )
        result["cost_registrations"] = [
            _model_to_dict(cr, exclude={"created_at", "updated_at"})
            for cr in cr_result.scalars().all()
        ]

        # --- Document folders ---
        from app.models.domain.document import Document
        from app.models.domain.document_entity_link import DocumentEntityLink
        from app.models.domain.document_folder import DocumentFolder
        from app.models.domain.document_version import DocumentVersion

        project_ids = [p["project_id"] for p in result["projects"]]

        df_result = await self.session.execute(
            select(DocumentFolder)
            .where(DocumentFolder.project_id.in_(project_ids))
            .order_by(DocumentFolder.id)
        )
        result["document_folders"] = [
            _model_to_dict(df, exclude={"created_at", "updated_at"})
            for df in df_result.scalars().all()
        ]

        # --- Documents ---
        doc_result = await self.session.execute(
            select(Document)
            .where(Document.project_id.in_(project_ids))
            .order_by(Document.id)
        )
        result["documents"] = [
            _model_to_dict(d, exclude={"created_at", "updated_at"})
            for d in doc_result.scalars().all()
        ]
        document_ids = [d["id"] for d in result["documents"]]

        # --- Document versions ---
        if document_ids:
            dv_result = await self.session.execute(
                select(DocumentVersion)
                .where(DocumentVersion.document_id.in_(document_ids))
                .order_by(DocumentVersion.id)
            )
        else:
            dv_result = await self.session.execute(
                select(DocumentVersion).where(text("false"))
            )
        result["document_versions"] = [
            _model_to_dict(dv, exclude={"created_at", "updated_at"})
            for dv in dv_result.scalars().all()
        ]

        # --- Document entity links ---
        if document_ids:
            del_result = await self.session.execute(
                select(DocumentEntityLink)
                .where(DocumentEntityLink.document_id.in_(document_ids))
                .order_by(DocumentEntityLink.id)
            )
        else:
            del_result = await self.session.execute(
                select(DocumentEntityLink).where(text("false"))
            )
        result["document_entity_links"] = [
            _model_to_dict(del_row, exclude={"created_at", "updated_at"})
            for del_row in del_result.scalars().all()
        ]

        # --- Change orders (current versions only) ---
        co_result = await self.session.execute(
            select(ChangeOrder)
            .where(
                ChangeOrder.branch == "main",
                func.upper(ChangeOrder.valid_time).is_(None),
            )
            .order_by(ChangeOrder.change_order_id)
        )
        result["change_orders"] = [
            _model_to_dict(co, exclude={"created_at", "updated_at"})
            for co in co_result.scalars().all()
        ]

        # --- Change order audit logs ---
        co_audit_result = await self.session.execute(
            select(ChangeOrderAuditLog).order_by(ChangeOrderAuditLog.changed_at)
        )
        result["change_order_audit_logs"] = [
            _model_to_dict(al, exclude={"created_at", "updated_at"})
            for al in co_audit_result.scalars().all()
        ]

        return result

    @staticmethod
    def validate_seed_data(data: dict[str, Any]) -> list[str]:
        """Validate seed data structure. Returns list of errors (empty = valid).

        Expects two-section format: ``{ system_config: {...}, projects: {...} }``
        """
        errors: list[str] = []

        if "system_config" not in data or "projects" not in data:
            errors.append("Seed data must have 'system_config' and 'projects' sections")
            return errors

        return SystemAdminService._validate_new_format(data)

    @staticmethod
    def _validate_new_format(data: dict[str, Any]) -> list[str]:
        """Validate the new two-section format."""
        errors: list[str] = []
        system_config = data.get("system_config", {})
        projects = data.get("projects", {})

        if not isinstance(system_config, dict):
            errors.append("'system_config' must be a dict")
            return errors
        if not isinstance(projects, dict):
            errors.append("'projects' must be a dict")
            return errors

        # Validate system_config sections
        sc_required = [
            "rbac_roles",
            "users",
            "user_role_assignments",
            "ai_providers",
            "ai_assistant_configs",
            "ai_specialist_configs",
            "mcp_servers",
            "change_order_workflow",
        ]
        for section in sc_required:
            if section not in system_config:
                errors.append(f"Missing system_config section: '{section}'")

        # Validate rbac_roles structure
        rbac_roles = system_config.get("rbac_roles")
        if isinstance(rbac_roles, dict):
            for role_name, role_def in rbac_roles.items():
                if not isinstance(role_def, dict):
                    errors.append(f"rbac_roles['{role_name}'] must be a dict")
                    continue
                if "description" not in role_def:
                    errors.append(f"rbac_roles['{role_name}'] missing 'description'")
                if "permissions" not in role_def:
                    errors.append(f"rbac_roles['{role_name}'] missing 'permissions'")
                elif not isinstance(role_def["permissions"], list):
                    errors.append(
                        f"rbac_roles['{role_name}']['permissions'] must be a list"
                    )

        # Validate users structure
        users = system_config.get("users")
        if isinstance(users, list):
            for i, user in enumerate(users):
                if not isinstance(user, dict):
                    errors.append(f"users[{i}] must be a dict")
                    continue
                for field in ("user_id", "email", "password", "full_name"):
                    if field not in user:
                        errors.append(f"users[{i}] missing '{field}'")

        # Validate user_role_assignments structure
        ura = system_config.get("user_role_assignments")
        if ura is not None and not isinstance(ura, dict):
            errors.append("user_role_assignments must be a dict")

        # Validate projects sections
        proj_required = [
            "organizational_units",
            "cost_element_types",
            "cost_event_types",
            "projects",
        ]
        for section in proj_required:
            if section not in projects:
                errors.append(f"Missing projects section: '{section}'")

        return errors

    async def reseed_from_upload(self, data: dict[str, Any]) -> dict[str, Any]:
        """Validate, truncate, and reseed from uploaded JSON.

        Returns a summary dict with counts of seeded entities.
        Accepts both the new two-section format and the old combined format.
        """
        from app.db.reseed import reseed_from_data, truncate_all_tables

        # 1. Validate
        errors = self.validate_seed_data(data)
        if errors:
            return {"success": False, "errors": errors}

        # 2. Merge two-section format into flat dict for reseed_from_data
        merged = self._merge_upload_data(data)

        # 3. Truncate
        await truncate_all_tables()

        # 4. Reseed
        await reseed_from_data(self.session, merged)

        # 5. Build summary
        return self._build_summary(merged)

    @staticmethod
    def _merge_upload_data(data: dict[str, Any]) -> dict[str, Any]:
        """Merge upload data into a flat dict for reseed_from_data.

        Expects two-section format with ``system_config`` and ``projects`` keys.
        """
        sc = data["system_config"]
        proj = data["projects"]
        merged: dict[str, Any] = {
            "_version": data.get("_version", 1),
            "_comment": data.get("_comment", ""),
            # System config sections
            "rbac_roles": sc.get("rbac_roles", {}),
            "users": sc.get("users", []),
            "user_role_assignments": sc.get("user_role_assignments", {}),
            "ai_providers": sc.get("ai_providers", []),
            "ai_assistant_configs": sc.get("ai_assistant_configs", []),
            "ai_specialist_configs": sc.get("ai_specialist_configs", []),
            "mcp_servers": sc.get("mcp_servers", []),
            "change_order_workflow": sc.get("change_order_workflow", {}),
            # Project sections (flat top-level arrays)
            "organizational_units": proj.get("organizational_units", []),
            "cost_element_types": proj.get("cost_element_types", []),
            "cost_event_types": proj.get("cost_event_types", []),
            "projects": proj.get("projects", []),
            "project_budget_settings": proj.get("project_budget_settings", []),
            "branches": proj.get("branches", []),
            "wbs_elements": proj.get("wbs_elements", []),
            "control_accounts": proj.get("control_accounts", []),
            "work_packages": proj.get("work_packages", []),
            "cost_elements": proj.get("cost_elements", []),
            "schedule_baselines": proj.get("schedule_baselines", []),
            "schedule_dependencies": proj.get("schedule_dependencies", []),
            "forecasts": proj.get("forecasts", []),
            "progress_entries": proj.get("progress_entries", []),
            "cost_events": proj.get("cost_events", []),
            "cost_registrations": proj.get("cost_registrations", []),
            "document_folders": proj.get("document_folders", []),
            "documents": proj.get("documents", []),
            "document_versions": proj.get("document_versions", []),
            "document_entity_links": proj.get("document_entity_links", []),
            "change_orders": proj.get("change_orders", []),
            "change_order_audit_logs": proj.get("change_order_audit_logs", []),
        }
        return merged

    @staticmethod
    def _build_summary(data: dict[str, Any]) -> dict[str, Any]:
        """Build a summary dict with counts of seeded entities."""
        summary: dict[str, Any] = {"success": True}
        summary["users"] = len(data.get("users", []))
        summary["rbac_roles"] = len(data.get("rbac_roles", {}))
        summary["ai_providers"] = len(data.get("ai_providers", []))
        summary["ai_assistant_configs"] = len(data.get("ai_assistant_configs", []))
        summary["ai_specialist_configs"] = len(data.get("ai_specialist_configs", []))
        summary["mcp_servers"] = len(data.get("mcp_servers", []))
        summary["organizational_units"] = len(data.get("organizational_units", []))
        summary["cost_element_types"] = len(data.get("cost_element_types", []))
        summary["cost_event_types"] = len(data.get("cost_event_types", []))

        project_entity_keys = [
            "projects",
            "project_budget_settings",
            "branches",
            "wbs_elements",
            "control_accounts",
            "work_packages",
            "cost_elements",
            "schedule_baselines",
            "schedule_dependencies",
            "forecasts",
            "progress_entries",
            "cost_events",
            "cost_registrations",
            "document_folders",
            "documents",
            "document_versions",
            "document_entity_links",
            "change_orders",
            "change_order_audit_logs",
        ]
        summary["project_entities"] = {
            key: len(data.get(key, [])) for key in project_entity_keys if data.get(key)
        }

        return summary
