import { useEffect, useMemo } from "react";
import { Button, Form, Input, DatePicker, Alert, Space } from "antd";
import { SaveOutlined, CloseOutlined } from "@ant-design/icons";
import dayjs from "dayjs";
import type {
  ChangeOrderPublic,
  ChangeOrderCreate,
  ChangeOrderUpdate,
} from "@/api/generated";
import { useWorkflowInfo } from "../hooks/useWorkflowInfo";

interface ChangeOrderFormSectionProps {
  projectId: string;
  changeOrder?: ChangeOrderPublic | null;
  onSave: (values: ChangeOrderCreate | ChangeOrderUpdate) => Promise<void>;
  onCancel: () => void;
  isLocked: boolean;
  existingCodes?: string[];
  isLoading?: boolean;
}

interface FormValues {
  code: string;
  title: string;
  description?: string;
  justification?: string;
  effective_date?: dayjs.Dayjs;
}

/**
 * Generate the next sequential change order code.
 * Format: CO-YYYY-NNN (e.g., CO-2026-001)
 */
function generateNextCode(existingCodes: string[]): string {
  const currentYear = new Date().getFullYear();
  const prefix = `CO-${currentYear}-`;

  const existingNumbers = existingCodes
    .filter((code) => code.startsWith(prefix))
    .map((code) => {
      const numStr = code.replace(prefix, "");
      const num = parseInt(numStr, 10);
      return isNaN(num) ? 0 : num;
    })
    .filter((n) => n > 0);

  const nextNumber = existingNumbers.length > 0 ? Math.max(...existingNumbers) + 1 : 1;
  return `${prefix}${String(nextNumber).padStart(3, "0")}`;
}

/**
 * ChangeOrderFormSection - Form section for creating/editing change orders.
 *
 * Displays all form fields for change order metadata including code,
 * title, status, effective date, description, and justification.
 *
 * Handles:
 * - Create mode (no changeOrder provided)
 * - Edit mode (changeOrder provided)
 * - Branch locked state (form disabled)
 * - Auto-generation of change order codes
 */
export function ChangeOrderFormSection({
  projectId,
  changeOrder,
  onSave,
  onCancel,
  isLocked,
  existingCodes = [],
  isLoading = false,
}: ChangeOrderFormSectionProps) {
  const [form] = Form.useForm();
  const isEdit = !!changeOrder;

  // Get workflow-aware information
  const workflowInfo = useWorkflowInfo(
    changeOrder?.status,
    changeOrder?.available_transitions,
    changeOrder?.can_edit_status,
    isLocked
  );

  // Auto-generate next code for new change orders
  const autoGeneratedCode = useMemo(() => {
    if (isEdit) return changeOrder?.code;
    return generateNextCode(existingCodes);
  }, [isEdit, changeOrder?.code, existingCodes]);

  useEffect(() => {
    if (changeOrder) {
      form.setFieldsValue({
        ...changeOrder,
        effective_date: changeOrder.effective_date
          ? dayjs(changeOrder.effective_date)
          : null,
      });
    } else {
      form.resetFields();
      form.setFieldsValue({
        project_id: projectId,
        status: "Draft",
        code: autoGeneratedCode,
      });
    }
  }, [changeOrder, form, projectId, autoGeneratedCode]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      const formattedValues: Omit<FormValues, "effective_date"> & {
        effective_date?: string;
        project_id: string;
      } = {
        ...values,
        project_id: projectId,
      };

      if (values.effective_date) {
        formattedValues.effective_date = values.effective_date.format("YYYY-MM-DD");
      } else {
        delete formattedValues.effective_date;
      }

      await onSave(formattedValues);
    } catch (error) {
      console.error("Form submission error:", error);
    }
  };

  return (
    <div style={{ marginBottom: 24 }}>
      <Form form={form} layout="vertical" disabled={isLocked}>
        <Form.Item name="project_id" initialValue={projectId} hidden>
          <Input />
        </Form.Item>

        {/* Warning banner when branch is locked */}
        {isLocked && workflowInfo.lockedBranchWarning && (
          <Alert
            type="warning"
            message="Branch Locked"
            description={workflowInfo.lockedBranchWarning}
            showIcon
            style={{ marginBottom: 16 }}
          />
        )}

        <Form.Item
          name="code"
          label="Change Order Code"
          rules={[
            { required: true, message: "Please enter change order code" },
            {
              pattern: /^CO-\d{4}-\d+$/i,
              message: 'Code must match format "CO-YYYY-NNN" (e.g., CO-2026-001)',
            },
          ]}
          tooltip='Format: CO-YYYY-NNN (e.g., "CO-2026-001")'
        >
          <Input
            placeholder="CO-2026-001"
            disabled={isEdit}
            addonAfter={
              <span style={{ fontSize: "11px", color: "#888" }}>
                Branch: co-{form.getFieldValue("code") || autoGeneratedCode}
              </span>
            }
          />
        </Form.Item>

        <Form.Item
          name="title"
          label="Title"
          rules={[{ required: true, message: "Please enter a title" }]}
        >
          <Input placeholder="Brief title for the change order" />
        </Form.Item>

        <Form.Item name="effective_date" label="Effective Date">
          <DatePicker style={{ width: "100%" }} disabled={isLocked} />
        </Form.Item>

        <Form.Item
          name="description"
          label="Description"
          rules={[
            { required: true, message: "Please enter a description" },
            { min: 20, message: "Description must be at least 20 characters" },
          ]}
        >
          <Input.TextArea
            placeholder="Detailed description of the change..."
            rows={4}
          />
        </Form.Item>

        <Form.Item
          name="justification"
          label="Justification"
          tooltip="Business justification for this change"
        >
          <Input.TextArea
            placeholder="Explain why this change is necessary..."
            rows={3}
          />
        </Form.Item>

        {/* Action buttons */}
        <Form.Item style={{ marginBottom: 0 }}>
          <Space>
            <Button
              type="primary"
              icon={<SaveOutlined />}
              onClick={handleSubmit}
              loading={isLoading}
              disabled={isLocked}
            >
              Save
            </Button>
            <Button
              icon={<CloseOutlined />}
              onClick={onCancel}
              disabled={isLoading}
            >
              Cancel
            </Button>
          </Space>
        </Form.Item>
      </Form>

      {!isEdit && (
        <div
          style={{
            marginTop: "16px",
            padding: "12px",
            backgroundColor: "#f0f5ff",
            borderRadius: "6px",
            fontSize: "13px",
            color: "#595959",
          }}
        >
          <strong>Note:</strong> Creating this change order will automatically
          create a branch named{" "}
          <code>co-{autoGeneratedCode}</code> for isolated
          development of changes.
        </div>
      )}
    </div>
  );
}
