import { useEffect, useMemo } from "react";
import { Modal, Form, Input, DatePicker, Select, Alert } from "antd";
import dayjs from "dayjs";
import type {
  ChangeOrderPublic,
  ChangeOrderCreate,
  ChangeOrderUpdate,
} from "@/api/generated";
import { useWorkflowInfo } from "../hooks/useWorkflowInfo";

interface ChangeOrderModalProps {
  open: boolean;
  onCancel: () => void;
  onOk: (values: ChangeOrderCreate | ChangeOrderUpdate) => void;
  confirmLoading: boolean;
  initialValues?: ChangeOrderPublic | null;
  projectId: string; // Project ID is required for creating change orders
  existingCodes?: string[]; // Existing codes to auto-generate next sequential
}

interface FormValues {
  code: string;
  title: string;
  description?: string;
  justification?: string;
  effective_date?: dayjs.Dayjs;
  status: string;
}

/**
 * Generate the next sequential change order code.
 * Format: CO-YYYY-NNN (e.g., CO-2026-001)
 */
function generateNextCode(existingCodes: string[]): string {
  const currentYear = new Date().getFullYear();
  const prefix = `CO-${currentYear}-`;

  // Extract numeric parts from existing codes for current year
  const existingNumbers = existingCodes
    .filter((code) => code.startsWith(prefix))
    .map((code) => {
      const numStr = code.replace(prefix, "");
      const num = parseInt(numStr, 10);
      return isNaN(num) ? 0 : num;
    })
    .filter((n) => n > 0);

  // Find the highest number and add 1
  const nextNumber = existingNumbers.length > 0 ? Math.max(...existingNumbers) + 1 : 1;

  // Format with zero-padding (e.g., 001, 002, 999, 1000)
  return `${prefix}${String(nextNumber).padStart(3, "0")}`;
}

export const ChangeOrderModal = ({
  open,
  onCancel,
  onOk,
  confirmLoading,
  initialValues,
  projectId,
  existingCodes = [],
}: ChangeOrderModalProps) => {
  const [form] = Form.useForm();
  const isEdit = !!initialValues;

  // Get workflow-aware information
  const workflowInfo = useWorkflowInfo(
    initialValues?.status,
    initialValues?.available_transitions,
    initialValues?.can_edit_status,
    initialValues?.branch_locked
  );

  // Auto-generate next code for new change orders
  const autoGeneratedCode = useMemo(() => {
    if (isEdit) return initialValues?.code;
    return generateNextCode(existingCodes);
  }, [isEdit, initialValues?.code, existingCodes]);

  useEffect(() => {
    if (open) {
      if (initialValues) {
        // Transform API date strings to dayjs objects for DatePicker
        form.setFieldsValue({
          ...initialValues,
          effective_date: initialValues.effective_date
            ? dayjs(initialValues.effective_date)
            : null,
        });
      } else {
        form.resetFields();
        // Pre-set project_id, default status, and auto-generated code
        form.setFieldsValue({
          project_id: projectId,
          status: "Draft",
          code: autoGeneratedCode,
        });
      }
    }
  }, [open, initialValues, form, projectId, autoGeneratedCode]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      // Transform dayjs objects back to strings for API
      // Remove effective_date if not set (don't send null)
      const formattedValues: Omit<FormValues, "effective_date"> & { effective_date?: string; project_id: string } = {
        ...values,
        project_id: projectId, // Ensure project_id is always set
      };

      // Only include effective_date if a date is selected
      if (values.effective_date) {
        formattedValues.effective_date = values.effective_date.format("YYYY-MM-DD");
      } else {
        delete formattedValues.effective_date;
      }

      await onOk(formattedValues);
    } catch (error) {
      console.error("Form submission error:", error);
    }
  };

  return (
    <Modal
      title={isEdit ? "Edit Change Order" : "Create Change Order"}
      open={open}
      onCancel={onCancel}
      onOk={handleSubmit}
      okText={isEdit ? "Save" : "Create"}
      confirmLoading={confirmLoading}
      destroyOnClose
      width={700}
    >
      {/* Warning banner when branch is locked */}
      {workflowInfo.lockedBranchWarning && (
        <Alert
          type="warning"
          message="Branch Locked"
          description={workflowInfo.lockedBranchWarning}
          showIcon
          style={{ marginBottom: 16 }}
        />
      )}

      <Form form={form} layout="vertical" name="change_order_form">
        <Form.Item
          name="project_id"
          initialValue={projectId}
          hidden
        >
          <Input />
        </Form.Item>

        <Form.Item
          name="code"
          label="Change Order Code"
          rules={[
            { required: true, message: "Please enter change order code" },
            {
              pattern: /^CO-\d{4}-\d+$/i,
              message: 'Code must match format "CO-YYYY-NNN" (e.g., CO-2026-001)',
            },
          ]}
          tooltip='Format: CO-YYYY-NNN (e.g., "CO-2026-001")'
        >
          <Input
            placeholder="CO-2026-001"
            disabled={isEdit}
            addonAfter={
              <span style={{ fontSize: "11px", color: "#888" }}>
                Branch: co-{form.getFieldValue("code") || autoGeneratedCode}
              </span>
            }
          />
        </Form.Item>

        <Form.Item
          name="title"
          label="Title"
          rules={[{ required: true, message: "Please enter a title" }]}
        >
          <Input placeholder="Brief title for the change order" />
        </Form.Item>

        <Form.Item
          name="status"
          label="Status"
          rules={[{ required: true, message: "Please select status" }]}
          initialValue="Draft"
          tooltip={
            workflowInfo.isStatusDisabled
              ? workflowInfo.isBranchLocked
                ? "Status cannot be changed while branch is locked"
                : "Status cannot be edited in current workflow state"
              : undefined
          }
        >
          <Select
            options={workflowInfo.statusOptions}
            disabled={workflowInfo.isStatusDisabled}
          />
        </Form.Item>

        <Form.Item name="effective_date" label="Effective Date">
          <DatePicker style={{ width: "100%" }} />
        </Form.Item>

        <Form.Item
          name="description"
          label="Description"
          rules={[
            { required: true, message: "Please enter a description" },
            { min: 20, message: "Description must be at least 20 characters" },
          ]}
        >
          <Input.TextArea
            placeholder="Detailed description of the change..."
            rows={4}
          />
        </Form.Item>

        <Form.Item
          name="justification"
          label="Justification"
          tooltip="Business justification for this change"
        >
          <Input.TextArea
            placeholder="Explain why this change is necessary..."
            rows={3}
          />
        </Form.Item>
      </Form>

      {!isEdit && (
        <div
          style={{
            marginTop: "16px",
            padding: "12px",
            backgroundColor: "#f0f5ff",
            borderRadius: "6px",
            fontSize: "13px",
            color: "#595959",
          }}
        >
          <strong>Note:</strong> Creating this change order will automatically
          create a branch named{" "}
          <code>co-{autoGeneratedCode}</code> for isolated
          development of changes.
        </div>
      )}
    </Modal>
  );
};
