import { useEffect, useMemo, useState } from "react";
import {
  Modal,
  Form,
  Input,
  InputNumber,
  DatePicker,
  Select,
  Alert,
  Divider,
  theme,
} from "antd";
import dayjs from "dayjs";
import type {
  ChangeOrderPublic,
  ChangeOrderCreate,
  ChangeOrderUpdate,
  ChangeOrderStatus,
} from "@/api/generated";
import { useWorkflowInfo } from "../hooks/useWorkflowInfo";
import { useNextChangeOrderCode } from "../api/useChangeOrders";
import {
  useGlobalConfig,
  useProjectConfig,
  type CustomFieldDefinition,
} from "../api/useWorkflowConfig";

interface ServerErrors {
  code?: string;
}

interface ChangeOrderModalProps {
  open: boolean;
  onCancel: () => void;
  onOk: (values: ChangeOrderCreate | ChangeOrderUpdate) => void;
  confirmLoading: boolean;
  initialValues?: ChangeOrderPublic | null;
  projectId: string; // Project ID is required for creating change orders
  serverErrors?: ServerErrors; // Server-side validation errors to display
}

interface FormValues {
  code: string;
  title: string;
  description?: string;
  justification?: string;
  effective_date?: dayjs.Dayjs;
  status: string;
  custom_field_values?: Record<string, string | number | dayjs.Dayjs | null>;
}

export const ChangeOrderModal = ({
  open,
  onCancel,
  onOk,
  confirmLoading,
  initialValues,
  projectId,
  serverErrors,
}: ChangeOrderModalProps) => {
  const { token } = theme.useToken();
  const [form] = Form.useForm();
  const isEdit = !!initialValues;

  // Track current code value for branch name display
  const [currentCode, setCurrentCode] = useState<string>("");

  // Get workflow-aware information
  const workflowInfo = useWorkflowInfo(
    initialValues?.status,
    initialValues?.available_transitions,
    initialValues?.can_edit_status,
    initialValues?.branch_locked
  );

  // Fetch workflow config for custom fields (project with global fallback)
  const globalConfigQuery = useGlobalConfig();
  const projectConfigQuery = useProjectConfig(projectId, {
    enabled: !!projectId,
    retry: false,
  });

  const customFields: CustomFieldDefinition[] = useMemo(() => {
    const activeConfig =
      projectId && projectConfigQuery.data
        ? projectConfigQuery.data
        : globalConfigQuery.data;
    return activeConfig?.custom_fields ?? [];
  }, [projectId, projectConfigQuery.data, globalConfigQuery.data]);

  // Fetch next code from backend for create mode
  const { data: nextCodeData, isLoading: isLoadingNextCode } =
    useNextChangeOrderCode(isEdit ? undefined : projectId);

  // Auto-generated code from backend
  const autoGeneratedCode = isEdit
    ? initialValues?.code
    : nextCodeData?.code;

  // Use serverErrors directly from props - no local state needed
  const currentErrors = serverErrors || {};

  useEffect(() => {
    if (open) {
      if (initialValues) {
        // Transform API date strings to dayjs objects for DatePicker
        // Pre-fill custom field values, converting date strings to dayjs
        const cfv = initialValues.custom_field_values;
        const customFieldValues: Record<
          string,
          string | number | dayjs.Dayjs | null
        > = {};
        if (cfv) {
          for (const [key, value] of Object.entries(cfv)) {
            const fieldDef = customFields.find((f) => f.name === key);
            if (fieldDef?.type === "date" && typeof value === "string" && value) {
              customFieldValues[key] = dayjs(value);
            } else {
              customFieldValues[key] = value as string | number | null;
            }
          }
        }

        form.setFieldsValue({
          ...initialValues,
          effective_date: initialValues.effective_date
            ? dayjs(initialValues.effective_date)
            : null,
          custom_field_values:
            Object.keys(customFieldValues).length > 0
              ? customFieldValues
              : undefined,
        });
      } else {
        form.resetFields();
        // Pre-set project_id, default status, and auto-generated code
        form.setFieldsValue({
          project_id: projectId,
          status: "Draft",
          code: autoGeneratedCode || "",
        });
      }
    }
  }, [open, initialValues, form, projectId, autoGeneratedCode, customFields]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      // Destructure to separate effective_date from the rest,
      // then rebuild the payload with proper serialization.
      // This avoids the dayjs object leaking into the spread
      // and being silently dropped by JSON.stringify.
      const { effective_date, ...restValues } = values;

      const formattedValues: Omit<FormValues, "effective_date"> & {
        effective_date?: string;
        project_id: string;
      } = {
        ...restValues,
        project_id: projectId, // Ensure project_id is always set
      };

      // Only include effective_date if a valid dayjs date is selected
      if (effective_date && dayjs.isDayjs(effective_date) && effective_date.isValid()) {
        formattedValues.effective_date = effective_date.format("YYYY-MM-DD");
      }
      // When effective_date is null/undefined/invalid, omit it entirely
      // (don't send null to the API)

      // Convert custom field dayjs values to ISO strings for the API
      if (values.custom_field_values) {
        const cfv: Record<string, string | number | null> = {};
        for (const [key, value] of Object.entries(
          values.custom_field_values,
        )) {
          if (dayjs.isDayjs(value)) {
            cfv[key] = value.isValid() ? value.format("YYYY-MM-DD") : null;
          } else {
            cfv[key] = value as string | number | null;
          }
        }
        formattedValues.custom_field_values = cfv;
      }

      await onOk({
        ...formattedValues,
        status: formattedValues.status as ChangeOrderStatus,
      } as ChangeOrderCreate | ChangeOrderUpdate);
    } catch (error) {
      console.error("Form submission error:", error);
    }
  };

  return (
    <Modal
      title={isEdit ? "Edit Change Order" : "Create Change Order"}
      open={open}
      onCancel={onCancel}
      onOk={handleSubmit}
      okText={isEdit ? "Save" : "Create"}
      confirmLoading={confirmLoading}
      destroyOnHidden
      width={700}
    >
      {/* Warning banner when branch is locked */}
      {workflowInfo.lockedBranchWarning && (
        <Alert
          type="warning"
          title="Branch Locked"
          description={workflowInfo.lockedBranchWarning}
          showIcon
          style={{ marginBottom: token.marginMD }}
        />
      )}

      <Form
        form={form}
        layout="vertical"
        name="change_order_form"
        onValuesChange={(changedValues) => {
          // Track code changes for branch name display
          if ("code" in changedValues) {
            setCurrentCode(changedValues.code);
          }
        }}
      >
        <Form.Item
          name="project_id"
          initialValue={projectId}
          hidden
        >
          <Input />
        </Form.Item>

        <Form.Item
          name="code"
          label="Change Order Code"
          rules={[
            { required: true, message: "Please enter change order code" },
            {
              pattern: /^CO-\d{4}-\d+$/i,
              message: 'Code must match format "CO-YYYY-NNN" (e.g., CO-2026-001)',
            },
          ]}
          tooltip='Format: CO-YYYY-NNN (e.g., "CO-2026-001")'
          validateStatus={currentErrors.code ? "error" : undefined}
          help={currentErrors.code}
        >
          <Input
            placeholder={isLoadingNextCode ? "Loading..." : "CO-2026-001"}
            disabled={isEdit}
            addonAfter={
              <span style={{ fontSize: token.fontSizeXS, color: token.colorTextTertiary }}>
                Branch: BR-{currentCode || autoGeneratedCode || "..."}
              </span>
            }
          />
        </Form.Item>

        <Form.Item
          name="title"
          label="Title"
          rules={[{ required: true, message: "Please enter a title" }]}
        >
          <Input placeholder="Brief title for the change order" />
        </Form.Item>

        <Form.Item
          name="status"
          label="Status"
          rules={[{ required: true, message: "Please select status" }]}
          initialValue="Draft"
          tooltip={
            workflowInfo.isStatusDisabled
              ? workflowInfo.isBranchLocked
                ? "Status cannot be changed while branch is locked"
                : "Status cannot be edited in current workflow state"
              : undefined
          }
        >
          <Select
            options={workflowInfo.statusOptions}
            disabled={workflowInfo.isStatusDisabled}
          />
        </Form.Item>

        <Form.Item name="effective_date" label="Effective Date">
          <DatePicker style={{ width: "100%" }} />
        </Form.Item>

        <Form.Item
          name="description"
          label="Description"
          rules={[
            { required: true, message: "Please enter a description" },
            { min: 20, message: "Description must be at least 20 characters" },
          ]}
        >
          <Input.TextArea
            placeholder="Detailed description of the change..."
            rows={4}
          />
        </Form.Item>

        <Form.Item
          name="justification"
          label="Justification"
          tooltip="Business justification for this change"
        >
          <Input.TextArea
            placeholder="Explain why this change is necessary..."
            rows={3}
          />
        </Form.Item>

        {/* Dynamic Custom Fields */}
        {customFields.length > 0 && (
          <>
            <Divider style={{ margin: `${token.marginXS} 0` }}>
              Custom Fields
            </Divider>
            {customFields.map((field) => (
              <Form.Item
                key={field.name}
                name={["custom_field_values", field.name]}
                label={field.name}
                rules={[
                  {
                    required: field.required,
                    message: `${field.name} is required`,
                  },
                ]}
              >
                {field.type === "text" ? (
                  <Input placeholder={`Enter ${field.name.toLowerCase()}`} />
                ) : field.type === "number" ? (
                  <InputNumber
                    placeholder={`Enter ${field.name.toLowerCase()}`}
                    style={{ width: "100%" }}
                  />
                ) : field.type === "date" ? (
                  <DatePicker style={{ width: "100%" }} />
                ) : field.type === "select" && field.options.length > 0 ? (
                  <Select
                    placeholder={`Select ${field.name.toLowerCase()}`}
                    allowClear
                    options={field.options.map((opt) => ({
                      label: opt,
                      value: opt,
                    }))}
                  />
                ) : (
                  <Input placeholder={`Enter ${field.name.toLowerCase()}`} />
                )}
              </Form.Item>
            ))}
          </>
        )}
      </Form>

      {!isEdit && (
        <div
          style={{
            marginTop: token.marginMD,
            padding: token.marginSM,
            backgroundColor: token.colorInfoBg,
            borderRadius: token.borderRadius,
            fontSize: token.fontSizeSM,
            color: token.colorTextSecondary,
          }}
        >
          <strong>Note:</strong> Creating this change order will automatically
          create a branch named{" "}
          <code>BR-{currentCode || autoGeneratedCode || "..."}</code> for isolated
          development of changes.
        </div>
      )}
    </Modal>
  );
};
