import { useEffect } from "react";
import { Modal, Form, Input, DatePicker, Select, Alert, theme } from "antd";
import dayjs from "dayjs";
import type {
  ChangeOrderPublic,
  ChangeOrderCreate,
  ChangeOrderUpdate,
} from "@/api/generated";
import { useWorkflowInfo } from "../hooks/useWorkflowInfo";
import { useNextChangeOrderCode } from "../api/useChangeOrders";

interface ServerErrors {
  code?: string;
}

interface ChangeOrderModalProps {
  open: boolean;
  onCancel: () => void;
  onOk: (values: ChangeOrderCreate | ChangeOrderUpdate) => void;
  confirmLoading: boolean;
  initialValues?: ChangeOrderPublic | null;
  projectId: string; // Project ID is required for creating change orders
  serverErrors?: ServerErrors; // Server-side validation errors to display
}

interface FormValues {
  code: string;
  title: string;
  description?: string;
  justification?: string;
  effective_date?: dayjs.Dayjs;
  status: string;
}

export const ChangeOrderModal = ({
  open,
  onCancel,
  onOk,
  confirmLoading,
  initialValues,
  projectId,
  serverErrors,
}: ChangeOrderModalProps) => {
  const { token } = theme.useToken();
  const [form] = Form.useForm();
  const isEdit = !!initialValues;

  // Get workflow-aware information
  const workflowInfo = useWorkflowInfo(
    initialValues?.status,
    initialValues?.available_transitions,
    initialValues?.can_edit_status,
    initialValues?.branch_locked
  );

  // Fetch next code from backend for create mode
  const { data: nextCodeData, isLoading: isLoadingNextCode } =
    useNextChangeOrderCode(isEdit ? undefined : projectId);

  // Auto-generated code from backend
  const autoGeneratedCode = isEdit
    ? initialValues?.code
    : nextCodeData?.code;

  // Use serverErrors directly from props - no local state needed
  const currentErrors = serverErrors || {};

  useEffect(() => {
    if (open) {
      if (initialValues) {
        // Transform API date strings to dayjs objects for DatePicker
        form.setFieldsValue({
          ...initialValues,
          effective_date: initialValues.effective_date
            ? dayjs(initialValues.effective_date)
            : null,
        });
      } else {
        form.resetFields();
        // Pre-set project_id, default status, and auto-generated code
        form.setFieldsValue({
          project_id: projectId,
          status: "Draft",
          code: autoGeneratedCode || "",
        });
      }
    }
  }, [open, initialValues, form, projectId, autoGeneratedCode]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      // Transform dayjs objects back to strings for API
      // Remove effective_date if not set (don't send null)
      const formattedValues: Omit<FormValues, "effective_date"> & { effective_date?: string; project_id: string } = {
        ...values,
        project_id: projectId, // Ensure project_id is always set
      };

      // Only include effective_date if a date is selected
      if (values.effective_date) {
        formattedValues.effective_date = values.effective_date.format("YYYY-MM-DD");
      } else {
        delete formattedValues.effective_date;
      }

      await onOk(formattedValues);
    } catch (error) {
      console.error("Form submission error:", error);
    }
  };

  return (
    <Modal
      title={isEdit ? "Edit Change Order" : "Create Change Order"}
      open={open}
      onCancel={onCancel}
      onOk={handleSubmit}
      okText={isEdit ? "Save" : "Create"}
      confirmLoading={confirmLoading}
      destroyOnClose
      width={700}
    >
      {/* Warning banner when branch is locked */}
      {workflowInfo.lockedBranchWarning && (
        <Alert
          type="warning"
          message="Branch Locked"
          description={workflowInfo.lockedBranchWarning}
          showIcon
          style={{ marginBottom: token.marginMD }}
        />
      )}

      <Form form={form} layout="vertical" name="change_order_form">
        <Form.Item
          name="project_id"
          initialValue={projectId}
          hidden
        >
          <Input />
        </Form.Item>

        <Form.Item
          name="code"
          label="Change Order Code"
          rules={[
            { required: true, message: "Please enter change order code" },
            {
              pattern: /^CO-\d{4}-\d+$/i,
              message: 'Code must match format "CO-YYYY-NNN" (e.g., CO-2026-001)',
            },
          ]}
          tooltip='Format: CO-YYYY-NNN (e.g., "CO-2026-001")'
          validateStatus={currentErrors.code ? "error" : undefined}
          help={currentErrors.code}
        >
          <Input
            placeholder={isLoadingNextCode ? "Loading..." : "CO-2026-001"}
            disabled={isEdit}
            addonAfter={
              <span style={{ fontSize: token.fontSizeXS, color: token.colorTextTertiary }}>
                Branch: BR-{form.getFieldValue("code") || autoGeneratedCode || "..."}
              </span>
            }
          />
        </Form.Item>

        <Form.Item
          name="title"
          label="Title"
          rules={[{ required: true, message: "Please enter a title" }]}
        >
          <Input placeholder="Brief title for the change order" />
        </Form.Item>

        <Form.Item
          name="status"
          label="Status"
          rules={[{ required: true, message: "Please select status" }]}
          initialValue="Draft"
          tooltip={
            workflowInfo.isStatusDisabled
              ? workflowInfo.isBranchLocked
                ? "Status cannot be changed while branch is locked"
                : "Status cannot be edited in current workflow state"
              : undefined
          }
        >
          <Select
            options={workflowInfo.statusOptions}
            disabled={workflowInfo.isStatusDisabled}
          />
        </Form.Item>

        <Form.Item name="effective_date" label="Effective Date">
          <DatePicker style={{ width: "100%" }} />
        </Form.Item>

        <Form.Item
          name="description"
          label="Description"
          rules={[
            { required: true, message: "Please enter a description" },
            { min: 20, message: "Description must be at least 20 characters" },
          ]}
        >
          <Input.TextArea
            placeholder="Detailed description of the change..."
            rows={4}
          />
        </Form.Item>

        <Form.Item
          name="justification"
          label="Justification"
          tooltip="Business justification for this change"
        >
          <Input.TextArea
            placeholder="Explain why this change is necessary..."
            rows={3}
          />
        </Form.Item>
      </Form>

      {!isEdit && (
        <div
          style={{
            marginTop: token.marginMD,
            padding: token.marginSM,
            backgroundColor: token.colorInfoBg,
            borderRadius: token.borderRadius,
            fontSize: token.fontSizeSM,
            color: token.colorTextSecondary,
          }}
        >
          <strong>Note:</strong> Creating this change order will automatically
          create a branch named{" "}
          <code>BR-{autoGeneratedCode || "..."}</code> for isolated
          development of changes.
        </div>
      )}
    </Modal>
  );
};
