"""add presentation_prompt to ai_assistant_configs

Revision ID: 0174adcb05ff
Revises: 7e61a160474b
Create Date: 2026-06-03 14:23:30.448742

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0174adcb05ff'
down_revision: str | Sequence[str] | None = '7e61a160474b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: skip if column already exists (e.g. baseline create_all)
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = 'ai_assistant_configs' AND column_name = 'presentation_prompt'"
        )
    )
    if result.scalar() is None:
        with op.batch_alter_table('ai_assistant_configs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('presentation_prompt', sa.Text(), nullable=True, comment="Text injected into planner/supervisor/handoff prompts to describe this specialist's capabilities. Specialist-only."))

    # Data migration: copy description to presentation_prompt for existing specialists
    op.execute(
        "UPDATE ai_assistant_configs SET presentation_prompt = description WHERE agent_type = 'specialist' AND description IS NOT NULL"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assistant_configs', schema=None) as batch_op:
        batch_op.drop_column('presentation_prompt')

    # ### end Alembic commands ###
