"""add wbe table with project relationship

Revision ID: 48c88d1ddf9c
Revises: 605e2658577c
Create Date: 2026-01-05 16:56:53.308454

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "48c88d1ddf9c"
down_revision: str | Sequence[str] | None = "605e2658577c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
