"""add description to departments

Revision ID: 4af275505a7e
Revises: 6794f9bdb8c2
Create Date: 2026-01-06 08:42:53.741853

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4af275505a7e"
down_revision: str | Sequence[str] | None = "6794f9bdb8c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments", sa.Column("description", sa.String(length=5000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("departments", "description")
    # ### end Alembic commands ###
