"""enhance project table with code dates status

Revision ID: 605e2658577c
Revises: 8b73c9d2e3f4
Create Date: 2026-01-05 16:33:32.861674

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "605e2658577c"
down_revision: str | Sequence[str] | None = "8b73c9d2e3f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("code", sa.String(length=50), nullable=False))
    op.add_column(
        "projects",
        sa.Column("contract_value", sa.DECIMAL(precision=15, scale=2), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("start_date", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("end_date", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column("projects", sa.Column("status", sa.String(length=50), nullable=False))
    op.create_index(op.f("ix_projects_code"), "projects", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_code"), table_name="projects")
    op.drop_column("projects", "status")
    op.drop_column("projects", "end_date")
    op.drop_column("projects", "start_date")
    op.drop_column("projects", "contract_value")
    op.drop_column("projects", "code")
    # ### end Alembic commands ###
