"""add_audit_columns_to_versionable_mixin

Revision ID: 6794f9bdb8c2
Revises: 48c88d1ddf9c
Create Date: 2026-01-06 07:30:08.244606

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6794f9bdb8c2"
down_revision: str | Sequence[str] | None = "48c88d1ddf9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS wbes CASCADE")
    op.create_table(
        "wbes",
        sa.Column("wbe_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parent_wbe_id", sa.UUID(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "budget_allocation", sa.DECIMAL(precision=15, scale=2), nullable=False
        ),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "valid_time",
            postgresql.TSTZRANGE(),
            server_default=sa.text("tstzrange(now(), NULL, '[]')"),
            nullable=False,
        ),
        sa.Column(
            "transaction_time",
            postgresql.TSTZRANGE(),
            server_default=sa.text("tstzrange(now(), NULL, '[]')"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.Column("branch", sa.String(length=80), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("merge_from_branch", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wbes_code"), "wbes", ["code"], unique=False)
    op.create_index(op.f("ix_wbes_created_by"), "wbes", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_wbes_parent_wbe_id"), "wbes", ["parent_wbe_id"], unique=False
    )
    op.create_index(op.f("ix_wbes_project_id"), "wbes", ["project_id"], unique=False)
    op.create_index(op.f("ix_wbes_wbe_id"), "wbes", ["wbe_id"], unique=False)
    # Departments: Add created_by with system default, then remove default
    op.add_column(
        "departments",
        sa.Column(
            "created_by",
            sa.UUID(),
            server_default=sa.text("'00000000-0000-0000-0000-000000000000'"),
            nullable=False,
        ),
    )
    op.add_column("departments", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.alter_column(
        "departments", "created_by", server_default=None
    )  # Remove default after backfill
    op.create_index(
        op.f("ix_departments_created_by"), "departments", ["created_by"], unique=False
    )

    # Projects: Add created_by with system default
    op.add_column(
        "projects",
        sa.Column(
            "created_by",
            sa.UUID(),
            server_default=sa.text("'00000000-0000-0000-0000-000000000000'"),
            nullable=False,
        ),
    )
    op.add_column("projects", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.alter_column("projects", "created_by", server_default=None)
    op.create_index(
        op.f("ix_projects_created_by"), "projects", ["created_by"], unique=False
    )

    # Users: Add created_by with system default
    op.add_column(
        "users",
        sa.Column(
            "created_by",
            sa.UUID(),
            server_default=sa.text("'00000000-0000-0000-0000-000000000000'"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("deleted_by", sa.UUID(), nullable=True))
    op.alter_column("users", "created_by", server_default=None)
    op.create_index(op.f("ix_users_created_by"), "users", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_by"), table_name="users")
    op.drop_column("users", "deleted_by")
    op.drop_column("users", "created_by")
    op.drop_index(op.f("ix_projects_created_by"), table_name="projects")
    op.drop_column("projects", "deleted_by")
    op.drop_column("projects", "created_by")
    op.drop_index(op.f("ix_departments_created_by"), table_name="departments")
    op.drop_column("departments", "deleted_by")
    op.drop_column("departments", "created_by")
    op.drop_index(op.f("ix_wbes_wbe_id"), table_name="wbes")
    op.drop_index(op.f("ix_wbes_project_id"), table_name="wbes")
    op.drop_index(op.f("ix_wbes_parent_wbe_id"), table_name="wbes")
    op.drop_index(op.f("ix_wbes_created_by"), table_name="wbes")
    op.drop_index(op.f("ix_wbes_code"), table_name="wbes")
    op.drop_table("wbes")
    # ### end Alembic commands ###
