"""Unit tests for UserService.

Following TDD RED-GREEN-REFACTOR cycle.
"""

from uuid import uuid4

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.domain.user import User
from app.models.schemas.user import UserRegister, UserUpdate
from app.services.user import UserService


class TestUserServiceGetUser:
    """Test UserService.get_user() method."""

    @pytest.mark.asyncio
    async def test_get_user_returns_none_when_not_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user returns None for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act
        result = await service.get_user(non_existent_id)

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_get_user_returns_user_when_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user returns User when found."""
        # Arrange
        service = UserService(db_session)
        actor_id = uuid4()

        # Create a user directly in DB for testing
        user = User(
            user_id=uuid4(),
            email="test@example.com",
            hashed_password="hashed_pw",
            full_name="Test User",
            is_active=True,
            created_by=actor_id,
        )
        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        # Act
        result = await service.get_user(user.user_id)

        # Assert
        assert result is not None
        assert result.id == user.id
        assert result.email == "test@example.com"
        assert result.full_name == "Test User"

class TestUserServiceCreate:
    """Test UserService.create_user() method."""

    @pytest.mark.asyncio
    async def test_create_user_success(self, db_session: AsyncSession) -> None:
        """RED: Test successfully creating a user."""
        service = UserService(db_session)
        # user_id is now generated by service or not passed in Register
        user_in = UserRegister(
            email="newuser@example.com",
            password="secret_password",
            full_name="New User",
            role="editor",
            department="Engineering",
        )

        # Act
        created_user = await service.create_user(user_in, actor_id=uuid4())

        # Assert
        assert created_user is not None
        assert created_user.email == "newuser@example.com"
        assert created_user.user_id is not None
        # Verify persistence
        fetched = await service.get_user(created_user.user_id)
        assert fetched is not None
        assert fetched.email == "newuser@example.com"

class TestUserServiceUpdate:
    """Test UserService.update_user() method."""

    @pytest.mark.asyncio
    async def test_update_user_versions(self, db_session: AsyncSession) -> None:
        """RED: Test updating a user creates a new version."""
        service = UserService(db_session)
        user_in = UserRegister(
            email="update_test@example.com",
            password="secret_password",
            full_name="Original Name",
            role="user",
            department="Sales",
            is_active=True,
        )
        # Create initial version
        v1 = await service.create_user(user_in, actor_id=uuid4())
        user_id = v1.user_id
        v1_id = v1.id  # Capture ID before update may expire the instance

        # Act
        update_in = UserUpdate(full_name="Updated Name")
        v2 = await service.update_user(user_id, update_in, actor_id=uuid4())

        # Assert
        assert v2 is not None
        assert v2.id != v1_id  # Different version IDs
        assert v2.user_id == user_id  # Same user ID
        assert v2.full_name == "Updated Name"

        # Verify persistence of new version
        fetched = await service.get_user(v2.user_id)
        assert fetched is not None
        assert fetched.full_name == "Updated Name"

class TestUserServiceDelete:
    """Test UserService.delete_user() method."""

    @pytest.mark.asyncio
    async def test_delete_user_soft_deletes(self, db_session: AsyncSession) -> None:
        """RED: Test deleting a user soft-deletes the current version."""
        service = UserService(db_session)
        user_in = UserRegister(
            email="delete_test@example.com",
            password="secret_password",
            full_name="To Be Deleted",
            role="user",
            department="Engineering",
            is_active=True,
        )
        # Create user
        v1 = await service.create_user(user_in, actor_id=uuid4())
        user_id = v1.user_id

        # Act
        deleted_user = await service.delete_user(user_id, actor_id=uuid4())

        # Assert
        assert deleted_user is not None
        assert deleted_user.is_deleted is True
        assert deleted_user.deleted_at is not None

        # Verify persistence (get_user filters deleted_at)
        fetched = await service.get_user(v1.user_id)
        assert fetched is None

        # get_by_email should return None for deleted users
        result = await service.get_by_email("delete_test@example.com")
        assert result is None

    @pytest.mark.asyncio
    async def test_delete_user_raises_when_not_found(
        self, db_session: AsyncSession
    ) -> None:
        """Test that delete_user raises ValueError when user doesn't exist."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act & Assert
        with pytest.raises(
            ValueError, match=f"No active version found for {non_existent_id}"
        ):
            await service.delete_user(non_existent_id, actor_id=uuid4())

class TestServiceGetById:
    """Test UserService.get_by_id() method - PK lookup."""

    @pytest.mark.asyncio
    async def test_get_by_id_returns_none_when_not_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_by_id returns None for non-existent PK."""
        # Arrange
        service = UserService(db_session)
        non_existent_pk = uuid4()

        # Act
        result = await service.get_by_id(non_existent_pk)

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_get_by_id_returns_user_when_found(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_by_id returns User when found by PK."""
        # Arrange
        service = UserService(db_session)
        actor_id = uuid4()

        # Create a user directly in DB for testing
        user = User(
            user_id=uuid4(),
            email="test@example.com",
            hashed_password="hashed_pw",
            full_name="Test User",
            is_active=True,
            created_by=actor_id,
        )
        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        # Act - get_by_id uses PK (id), not user_id
        result = await service.get_by_id(user.id)

        # Assert
        assert result is not None
        assert result.id == user.id
        assert result.email == "test@example.com"
        assert result.full_name == "Test User"

    @pytest.mark.asyncio
    async def test_get_by_id_vs_get_user_difference(
        self, db_session: AsyncSession
    ) -> None:
        """Test that get_by_id uses PK while get_user uses user_id (root_id)."""
        # Arrange
        service = UserService(db_session)
        actor_id = uuid4()

        # Create a user
        user = User(
            user_id=uuid4(),
            email="distinction@example.com",
            hashed_password="hashed_pw",
            full_name="Distinction Test",
            is_active=True,
            created_by=actor_id,
        )
        db_session.add(user)
        await db_session.commit()
        await db_session.refresh(user)

        # Act & Assert
        # get_by_id uses PK (id) - should work
        result_by_pk = await service.get_by_id(user.id)
        assert result_by_pk is not None
        assert result_by_pk.id == user.id

        # get_user uses user_id (root_id) - should also work
        result_by_root = await service.get_user(user.user_id)
        assert result_by_root is not None
        assert result_by_root.user_id == user.user_id

        # Both return the same user
        assert result_by_pk.id == result_by_root.id

class TestUserServicePreferences:
    """Test UserService preference methods."""

    @pytest.mark.asyncio
    async def test_get_user_preferences_returns_empty_dict_for_new_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that get_user_preferences returns empty dict when user has no preferences."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="pref_test@example.com",
            password="secret_password",
            full_name="Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        prefs = await service.get_user_preferences(user.user_id)

        # Assert
        assert prefs == {}

class TestUserIdentifiers:
    """Test UserService user_id vs id (PK) resolution methods.

    These tests verify the architectural decision that:
    - get_user(user_id) uses EVCS root ID (user.user_id) - the canonical identifier
    - get_by_id(id) uses database PK (user.id) - for specific version lookups

    Context: BE-003 - Standardize user_id usage across services
    """

    @pytest.mark.asyncio
    async def test_get_user_vs_get_by_id_both_work_with_correct_identifiers(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user and get_by_id both work with correct identifiers.

        This test demonstrates:
        - get_user(user_id) works when called with user.user_id (EVCS root ID)
        - get_by_id(id) works when called with user.id (database PK)
        - Both return the same user entity
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="identifier_test@example.com",
            password="secret_password",
            full_name="Identifier Test",
            role="viewer",
        )
        created_user = await service.create_user(user_in, actor_id=uuid4())

        # Act & Assert
        # get_user should work with user.user_id (EVCS root ID)
        result_by_user_id = await service.get_user(created_user.user_id)
        assert result_by_user_id is not None
        assert result_by_user_id.user_id == created_user.user_id
        assert result_by_user_id.email == "identifier_test@example.com"

        # get_by_id should work with user.id (database PK)
        result_by_pk = await service.get_by_id(created_user.id)
        assert result_by_pk is not None
        assert result_by_pk.id == created_user.id
        assert result_by_pk.email == "identifier_test@example.com"

        # Both should return the same user entity
        assert result_by_user_id.id == result_by_pk.id
        assert result_by_user_id.user_id == result_by_pk.user_id

    @pytest.mark.asyncio
    async def test_get_user_fails_with_database_pk(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_user fails when called with database PK instead of user_id.

        This test demonstrates that get_user expects user.user_id (EVCS root ID),
        not user.id (database PK).
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="pk_test@example.com",
            password="secret_password",
            full_name="PK Test",
            role="viewer",
        )
        created_user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        # Try to call get_user with database PK (incorrect usage)
        result = await service.get_user(created_user.id)

        # Assert
        # Should return None because created_user.id is not a valid user_id
        assert result is None

    @pytest.mark.asyncio
    async def test_get_by_id_fails_with_evcs_root_id(
        self, db_session: AsyncSession
    ) -> None:
        """RED: Test that get_by_id fails when called with user_id instead of database PK.

        This test demonstrates that get_by_id expects user.id (database PK),
        not user.user_id (EVCS root ID).
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="root_id_test@example.com",
            password="secret_password",
            full_name="Root ID Test",
            role="viewer",
        )
        created_user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        # Try to call get_by_id with user.user_id (incorrect usage)
        result = await service.get_by_id(created_user.user_id)

        # Assert
        # Should return None because created_user.user_id is not a valid database PK
        assert result is None

    @pytest.mark.asyncio
    async def test_get_user_returns_current_active_version(
        self, db_session: AsyncSession
    ) -> None:
        """GREEN: Test that get_user always returns the current active version.

        This test verifies that get_user follows EVCS patterns and returns
        the current active version, not historical versions.
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="version_test@example.com",
            password="secret_password",
            full_name="Version Test Original",
            role="viewer",
        )
        v1 = await service.create_user(user_in, actor_id=uuid4())
        user_id = v1.user_id

        # Create a new version (update)
        update_in = UserUpdate(full_name="Version Test Updated")
        v2 = await service.update_user(user_id, update_in, actor_id=uuid4())

        # Act
        # get_user should return the current active version (v2)
        current = await service.get_user(user_id)

        # Assert
        assert current is not None
        assert current.user_id == user_id
        assert current.full_name == "Version Test Updated"
        assert current.id == v2.id  # Should be v2's PK

    @pytest.mark.asyncio
    async def test_get_by_id_returns_specific_version_by_pk(
        self, db_session: AsyncSession
    ) -> None:
        """GREEN: Test that get_by_id returns a specific version by PK.

        This test verifies that get_by_id can retrieve any specific version
        (including historical) by its database PK.
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="specific_version_test@example.com",
            password="secret_password",
            full_name="Specific Version Original",
            role="viewer",
        )
        v1 = await service.create_user(user_in, actor_id=uuid4())
        v1_id = v1.id  # Save v1's PK
        user_id = v1.user_id

        # Create a new version (update)
        update_in = UserUpdate(full_name="Specific Version Updated")
        v2 = await service.update_user(user_id, update_in, actor_id=uuid4())

        # Act
        # get_by_id with v1's PK should return v1 (historical version)
        historical = await service.get_by_id(v1_id)
        # get_by_id with v2's PK should return v2 (current version)
        current = await service.get_by_id(v2.id)

        # Assert
        assert historical is not None
        assert historical.id == v1_id
        assert historical.full_name == "Specific Version Original"

        assert current is not None
        assert current.id == v2.id
        assert current.full_name == "Specific Version Updated"

    @pytest.mark.asyncio
    async def test_get_user_after_soft_delete_returns_none(
        self, db_session: AsyncSession
    ) -> None:
        """GREEN: Test that get_user returns None for soft-deleted users.

        This test verifies that get_user respects soft deletes and returns
        None for deleted users, maintaining data isolation.
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="delete_test@example.com",
            password="secret_password",
            full_name="Delete Test",
            role="viewer",
        )
        user = await service.create_user(user_in, actor_id=uuid4())
        user_id = user.user_id

        # Soft delete the user
        await service.delete_user(user_id, actor_id=uuid4())

        # Act
        result = await service.get_user(user_id)

        # Assert
        assert result is None

    @pytest.mark.asyncio
    async def test_get_by_id_after_soft_delete_returns_deleted_version(
        self, db_session: AsyncSession
    ) -> None:
        """GREEN: Test that get_by_id can still retrieve soft-deleted user versions.

        This test verifies that get_by_id can retrieve historical versions
        even after soft delete, for audit trail purposes.
        """
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="delete_pk_test@example.com",
            password="secret_password",
            full_name="Delete PK Test",
            role="viewer",
        )
        user = await service.create_user(user_in, actor_id=uuid4())
        user_id = user.user_id
        user_pk = user.id

        # Soft delete the user
        deleted_user = await service.delete_user(user_id, actor_id=uuid4())
        deleted_user_pk = deleted_user.id

        # Act
        # get_by_id should still return the deleted version (for audit trail)
        result = await service.get_by_id(user_pk)
        deleted_result = await service.get_by_id(deleted_user_pk)

        # Assert
        # The original version should be retrievable by PK
        assert result is not None
        assert result.id == user_pk
        assert result.full_name == "Delete PK Test"

        # The deleted version should also be retrievable by PK
        assert deleted_result is not None
        assert deleted_result.id == deleted_user_pk
        assert deleted_result.is_deleted is True
        assert deleted_result.deleted_at is not None

    @pytest.mark.asyncio
    async def test_get_user_preferences_raises_for_nonexistent_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that get_user_preferences raises ValueError for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act & Assert
        with pytest.raises(ValueError, match="User .* not found"):
            await service.get_user_preferences(non_existent_id)

    @pytest.mark.asyncio
    async def test_update_user_preferences_creates_preferences(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences creates preferences for new user."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="update_pref@example.com",
            password="secret_password",
            full_name="Update Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act
        new_prefs = {"theme": "dark"}
        result = await service.update_user_preferences(user.user_id, new_prefs)
        await db_session.commit()

        # Assert
        assert result == {"theme": "dark"}

        # Verify persistence
        fetched_prefs = await service.get_user_preferences(user.user_id)
        assert fetched_prefs == {"theme": "dark"}

    @pytest.mark.asyncio
    async def test_update_user_preferences_merges_existing(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences merges with existing preferences."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="merge_pref@example.com",
            password="secret_password",
            full_name="Merge Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Set initial preferences
        await service.update_user_preferences(
            user.user_id, {"theme": "light", "locale": "en"}
        )
        await db_session.commit()

        # Act - update only theme
        result = await service.update_user_preferences(user.user_id, {"theme": "dark"})
        await db_session.commit()

        # Assert - theme updated, locale preserved
        assert result == {"theme": "dark", "locale": "en"}

        # Verify persistence
        fetched_prefs = await service.get_user_preferences(user.user_id)
        assert fetched_prefs == {"theme": "dark", "locale": "en"}

    @pytest.mark.asyncio
    async def test_update_user_preferences_raises_for_nonexistent_user(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences raises ValueError for non-existent user."""
        # Arrange
        service = UserService(db_session)
        non_existent_id = uuid4()

        # Act & Assert
        with pytest.raises(ValueError, match="User .* not found"):
            await service.update_user_preferences(non_existent_id, {"theme": "dark"})

    @pytest.mark.asyncio
    async def test_update_user_preferences_validates_theme(
        self, db_session: AsyncSession
    ) -> None:
        """Test that update_user_preferences validates theme values."""
        # Arrange
        service = UserService(db_session)
        user_in = UserRegister(
            email="validate_pref@example.com",
            password="secret_password",
            full_name="Validate Pref Test",
            role="user",
        )
        user = await service.create_user(user_in, actor_id=uuid4())

        # Act & Assert - valid themes should work
        result = await service.update_user_preferences(user.user_id, {"theme": "dark"})
        assert result["theme"] == "dark"

        result = await service.update_user_preferences(user.user_id, {"theme": "light"})
        assert result["theme"] == "light"

        # Extra fields should be allowed
        result = await service.update_user_preferences(
            user.user_id, {"theme": "dark", "locale": "en-US", "timezone": "UTC"}
        )
        assert result["theme"] == "dark"
        assert result["locale"] == "en-US"
        assert result["timezone"] == "UTC"
