/**
 * RBAC Admin API types.
 *
 * These types are NOT generated by openapi-typescript-codegen because the
 * RBAC admin endpoints live under /api/v1/admin/rbac which is not yet
 * included in the generated client. Update this file manually if the
 * backend schemas change, or regenerate the client once the endpoints
 * are added to the OpenAPI spec.
 */

export interface RBACPermissionRead {
  id: string;
  permission: string;
}

export interface RBACRoleRead {
  id: string;
  name: string;
  description: string | null;
  is_system: boolean;
  permissions: RBACPermissionRead[];
  created_at: string;
  updated_at: string;
}

export interface RBACRoleCreate {
  name: string;
  description?: string;
  permissions: string[];
}

export interface RBACRoleUpdate {
  name?: string;
  description?: string;
  permissions?: string[];
}

export interface RBACProviderStatus {
  provider: string;
  editable: boolean;
}
